# Generated by Django 2.0.5 on 2018-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20180727_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeroles',
            name='role',
            field=models.CharField(choices=[('office data entry', 'Office Data Entry'), ('ops executive', 'Ops Executive'), ('accounts payable', 'Accounts Payable'), ('accounts receivable', 'Accounts Receivable'), ('sales', 'Sales'), ('traffic', 'Traffic'), ('city head', 'City Head')], default='office data entry', max_length=35, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalemployeeroles',
            name='role',
            field=models.CharField(choices=[('office data entry', 'Office Data Entry'), ('ops executive', 'Ops Executive'), ('accounts payable', 'Accounts Payable'), ('accounts receivable', 'Accounts Receivable'), ('sales', 'Sales'), ('traffic', 'Traffic'), ('city head', 'City Head')], db_index=True, default='office data entry', max_length=35, null=True),
        ),
    ]
