# Generated by Django 2.0.5 on 2018-08-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20180727_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeerolesbookingstatusmapping',
            old_name='position',
            new_name='assignment_status',
        ),
        migrations.RenameField(
            model_name='historicalemployeerolesbookingstatusmapping',
            old_name='position',
            new_name='assignment_status',
        ),
        migrations.AlterField(
            model_name='bookingstatuses',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('loaded', 'Loaded'), ('lr_generated', 'Lr_Generated'), ('advance_paid', 'Advance_Paid'), ('reconciled', 'Reconciled'), ('unloaded', 'Unloaded'), ('pod_uploaded', 'PoD_Uploaded'), ('pod_verified', 'PoD_Verified'), ('invoice_raised', 'Invoice_Raised'), ('invoice_confirmed', 'Invoice Confirmed'), ('balance_paid', 'Balance_Paid'), ('party_invoice_sent', 'Party_Invoice_Sent'), ('inward_followup', 'Inward_Followup'), ('complete', 'Complete')], default='confirmed', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbookingstatuses',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('loaded', 'Loaded'), ('lr_generated', 'Lr_Generated'), ('advance_paid', 'Advance_Paid'), ('reconciled', 'Reconciled'), ('unloaded', 'Unloaded'), ('pod_uploaded', 'PoD_Uploaded'), ('pod_verified', 'PoD_Verified'), ('invoice_raised', 'Invoice_Raised'), ('invoice_confirmed', 'Invoice Confirmed'), ('balance_paid', 'Balance_Paid'), ('party_invoice_sent', 'Party_Invoice_Sent'), ('inward_followup', 'Inward_Followup'), ('complete', 'Complete')], default='confirmed', max_length=15, null=True),
        ),
    ]
