# Generated by Django 2.0.5 on 2018-08-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20180802_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingstatusesmapping',
            old_name='stage',
            new_name='booking_stage',
        ),
        migrations.RenameField(
            model_name='bookingstatusesmapping',
            old_name='booking',
            new_name='manual_booking',
        ),
        migrations.RenameField(
            model_name='historicalbookingstatusesmapping',
            old_name='stage',
            new_name='booking_stage',
        ),
        migrations.RenameField(
            model_name='historicalbookingstatusesmapping',
            old_name='booking',
            new_name='manual_booking',
        ),
    ]
