# Generated by Django 2.0.5 on 2018-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20180804_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaskdashboardfunctionalities',
            name='functionality',
            field=models.CharField(choices=[('pending_payments', 'Pending Payments'), ('pending_lr', 'Pending LR'), ('in_transit', 'In Transit'), ('invoice_confirmation', 'Invoice Confirmation'), ('customer_inquiries', 'Customer Inquiries'), ('open_inquiries', 'Open Inquiries'), ('new_inquiry', 'Submit New Inquiry'), ('my_inquiries', 'My Inquiries'), ('delivered', 'Delivered')], db_index=True, default='new_inquiry', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='taskdashboardfunctionalities',
            name='functionality',
            field=models.CharField(choices=[('pending_payments', 'Pending Payments'), ('pending_lr', 'Pending LR'), ('in_transit', 'In Transit'), ('invoice_confirmation', 'Invoice Confirmation'), ('customer_inquiries', 'Customer Inquiries'), ('open_inquiries', 'Open Inquiries'), ('new_inquiry', 'Submit New Inquiry'), ('my_inquiries', 'My Inquiries'), ('delivered', 'Delivered')], default='new_inquiry', max_length=35, null=True, unique=True),
        ),
    ]
