# Generated by Django 2.0.5 on 2018-08-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_auto_20180816_1343'),
        ('restapi', '0009_auto_20180813_1739'),
    ]

    operations = [
    ]
