# Generated by Django 2.0.5 on 2018-08-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20180820_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeroles',
            name='role',
            field=models.CharField(choices=[('office_data_entry', 'Office Data Entry'), ('ops_executive', 'Ops Executive'), ('accounts_payable', 'Accounts Payable'), ('accounts_receivable', 'Accounts Receivable'), ('sales', 'Sales'), ('traffic', 'Traffic'), ('city_head', 'City Head'), ('management', 'Management'), ('tech', 'Technology')], default='office_data_entry', max_length=35, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalemployeeroles',
            name='role',
            field=models.CharField(choices=[('office_data_entry', 'Office Data Entry'), ('ops_executive', 'Ops Executive'), ('accounts_payable', 'Accounts Payable'), ('accounts_receivable', 'Accounts Receivable'), ('sales', 'Sales'), ('traffic', 'Traffic'), ('city_head', 'City Head'), ('management', 'Management'), ('tech', 'Technology')], db_index=True, default='office_data_entry', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltaskdashboardfunctionalities',
            name='functionality',
            field=models.CharField(choices=[('new_inquiry', 'Submit New Inquiry'), ('customer_inquiries', 'Customer Inquiries'), ('open_inquiries', 'Open Inquiries'), ('my_inquiries', 'My Inquiries'), ('pending_payments', 'Pending Payments'), ('pending_lr', 'Pending LR'), ('in_transit', 'In Transit'), ('invoice_confirmation', 'Invoice Confirmation'), ('delivered', 'Delivered')], db_index=True, default='new_inquiry', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='taskdashboardfunctionalities',
            name='functionality',
            field=models.CharField(choices=[('new_inquiry', 'Submit New Inquiry'), ('customer_inquiries', 'Customer Inquiries'), ('open_inquiries', 'Open Inquiries'), ('my_inquiries', 'My Inquiries'), ('pending_payments', 'Pending Payments'), ('pending_lr', 'Pending LR'), ('in_transit', 'In Transit'), ('invoice_confirmation', 'Invoice Confirmation'), ('delivered', 'Delivered')], default='new_inquiry', max_length=35, null=True, unique=True),
        ),
    ]
