# Generated by Django 2.0.5 on 2018-08-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_auto_20180823_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerolesfunctionalitymapping',
            name='caption',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployeerolesfunctionalitymapping',
            name='caption',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
