# Generated by Django 2.0.5 on 2018-08-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_auto_20180828_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerolesmapping',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_role_mapping', to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='employeerolesmapping',
            name='employee_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_role', to='restapi.EmployeeRoles'),
        ),
    ]
