# Generated by Django 2.0.5 on 2018-09-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0015_auto_20180904_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaskdashboardfunctionalities',
            name='functionality',
            field=models.CharField(choices=[('new_inquiry', 'Submit New Inquiry'), ('customer_inquiries', 'Customer Inquiries'), ('open_inquiries', 'Open Inquiries'), ('my_inquiries', 'My Inquiries'), ('pending_payments', 'Pending Payments'), ('pending_lr', 'Pending LR'), ('in_transit', 'In Transit'), ('invoice_confirmation', 'Invoice Confirmation'), ('delivered', 'Delivered'), ('confirm_booking', 'New Booking'), ('lr_generation', 'Generate LR'), ('pay_advance', 'Pay Advance'), ('pay_balance', 'Pay Balance'), ('send_invoice', 'Send Invoice'), ('verify_pod', 'Verify PoD'), ('raise_invoice', 'Raise Invoice'), ('confirm_invoice', 'Confirm Invoice'), ('inward_entry', 'Inward Entry'), ('process_payments', 'Process Payments'), ('reconcile', 'Reconcile')], db_index=True, default='new_inquiry', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='taskdashboardfunctionalities',
            name='functionality',
            field=models.CharField(choices=[('new_inquiry', 'Submit New Inquiry'), ('customer_inquiries', 'Customer Inquiries'), ('open_inquiries', 'Open Inquiries'), ('my_inquiries', 'My Inquiries'), ('pending_payments', 'Pending Payments'), ('pending_lr', 'Pending LR'), ('in_transit', 'In Transit'), ('invoice_confirmation', 'Invoice Confirmation'), ('delivered', 'Delivered'), ('confirm_booking', 'New Booking'), ('lr_generation', 'Generate LR'), ('pay_advance', 'Pay Advance'), ('pay_balance', 'Pay Balance'), ('send_invoice', 'Send Invoice'), ('verify_pod', 'Verify PoD'), ('raise_invoice', 'Raise Invoice'), ('confirm_invoice', 'Confirm Invoice'), ('inward_entry', 'Inward Entry'), ('process_payments', 'Process Payments'), ('reconcile', 'Reconcile')], default='new_inquiry', max_length=35, null=True, unique=True),
        ),
    ]
