# Generated by Django 2.0.5 on 2018-09-10 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0016_auto_20180906_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstatusesmappingcomments',
            name='booking_status_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_status_mapping_comments', to='restapi.BookingStatusesMapping'),
        ),
        migrations.AddField(
            model_name='historicalbookingstatusesmappingcomments',
            name='booking_status_mapping',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='restapi.BookingStatusesMapping'),
        ),
    ]
