# Generated by Django 2.0.5 on 2018-10-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0022_auto_20181003_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatuses',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('loaded', 'Loaded'), ('lr_generated', 'Lr Generated'), ('advance_paid', 'Advance Paid'), ('unloaded', 'Unloaded'), ('pod_uploaded', 'PoD Uploaded'), ('pod_verified', 'PoD Verified'), ('invoice_raised', 'Invoice Raised'), ('invoice_confirmed', 'Invoice Confirmed'), ('balance_paid', 'Balance Paid'), ('party_invoice_sent', 'Party Invoice Sent'), ('inward_followup_completed', 'Inward Followup Completed'), ('complete', 'Complete')], default='confirmed', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='bookingstatusesmapping',
            name='booking_stage',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done'), ('reverted', 'Reverted'), ('escalated', 'Escalated')], default='in_progress', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbookingstatuses',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('loaded', 'Loaded'), ('lr_generated', 'Lr Generated'), ('advance_paid', 'Advance Paid'), ('unloaded', 'Unloaded'), ('pod_uploaded', 'PoD Uploaded'), ('pod_verified', 'PoD Verified'), ('invoice_raised', 'Invoice Raised'), ('invoice_confirmed', 'Invoice Confirmed'), ('balance_paid', 'Balance Paid'), ('party_invoice_sent', 'Party Invoice Sent'), ('inward_followup_completed', 'Inward Followup Completed'), ('complete', 'Complete')], default='confirmed', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbookingstatusesmapping',
            name='booking_stage',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done'), ('reverted', 'Reverted'), ('escalated', 'Escalated')], default='in_progress', max_length=15, null=True),
        ),
    ]
