# Generated by Django 2.0.2 on 2019-02-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0023_auto_20181029_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerolesfunctionalitymapping',
            name='access',
            field=models.CharField(choices=[('read_only', 'Read Only'), ('edit', 'Edit')], default='edit', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeerolesfunctionalitymapping',
            name='access',
            field=models.CharField(choices=[('read_only', 'Read Only'), ('edit', 'Edit')], default='edit', max_length=20, null=True),
        ),
    ]
