# Generated by Django 2.0.2 on 2019-02-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0024_auto_20190213_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstatusesmapping',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbookingstatusesmapping',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
