# Generated by Django 2.0.2 on 2019-02-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0025_auto_20190218_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaskdashboardfunctionalities',
            name='consumer',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('all', 'All')], default='web', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='taskdashboardfunctionalities',
            name='consumer',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('all', 'All')], default='web', max_length=35, null=True),
        ),
    ]
