# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='is_verified',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10, null=True),
        ),
    ]
