# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_databaseupdatelog_fieldchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aahooffice',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aahooffice',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
