# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20170520_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='aahooffice',
            name='branch_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
