# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_bankholidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategory',
            name='capacity',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
