# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-07 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_auto_20180112_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
