# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 14:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_auto_20180412_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='pin_code',
            field=models.PositiveIntegerField(db_index=True, unique=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(110003)]),
        ),
        migrations.AlterUniqueTogether(
            name='pincode',
            unique_together=set([('sub_district', 'pin_code'), ('latitude', 'longitude')]),
        ),
    ]
