# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_auto_20180417_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategory',
            name='capacity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
