# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_auto_20180417_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='aahooffice',
            name='t1_name',
            field=models.CharField(max_length=35, null=True, verbose_name='Traffic Person 1 Name'),
        ),
        migrations.AddField(
            model_name='aahooffice',
            name='t1_phone',
            field=models.CharField(help_text='enter 10 digit mobile number', max_length=10, null=True, verbose_name='Traffic Person 1 Phone'),
        ),
        migrations.AddField(
            model_name='aahooffice',
            name='t2_name',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Traffic Person 2 Name'),
        ),
        migrations.AddField(
            model_name='aahooffice',
            name='t2_phone',
            field=models.CharField(help_text='enter 10 digit mobile number', max_length=10, null=True, verbose_name='Traffic Person 2 Phone'),
        ),
    ]
