# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_auto_20180428_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aahooffice',
            name='t2_phone',
            field=models.CharField(blank=True, help_text='enter 10 digit mobile number', max_length=10, null=True, verbose_name='Traffic Person 2 Phone'),
        ),
    ]
