# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_auto_20180505_1231'),
        ('utils', '0017_auto_20180507_1145'),
    ]

    operations = [
    ]
