# Generated by Django 2.0.2 on 2018-05-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0019_auto_20180513_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclecategory',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Vehicle Category'},
        ),
    ]
