# Generated by Django 2.0.5 on 2018-08-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0022_auto_20180622_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
