# Generated by Django 2.0.5 on 2018-08-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0024_citylocal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylocal',
            name='hindi_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
