# Generated by Django 2.0.5 on 2018-08-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0025_auto_20180821_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylocal',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_local', to='utils.City', unique=True),
        ),
    ]
