# Generated by Django 2.0.5 on 2019-03-13 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0027_auto_20180821_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['-id'], 'verbose_name_plural': 'States'},
        ),
    ]
