# Generated by Django 2.0.5 on 2019-03-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0028_aahoholidays'),
        ('utils', '0028_auto_20190313_0105'),
    ]

    operations = [
    ]
