# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inwardpayment',
            name='booking',
        ),
        migrations.AddField(
            model_name='inwardpayment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inward_payments', to='supplier.Booking'),
        ),
        migrations.RemoveField(
            model_name='outwardpayment',
            name='booking',
        ),
        migrations.AddField(
            model_name='outwardpayment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outward_payments', to='supplier.Booking'),
        ),
    ]
