# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20170524_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardpayment',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='outwardpayment',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
        migrations.AlterField(
            model_name='inwardpayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='outwardpayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT')], max_length=70, null=True),
        ),
    ]
