# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20170524_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
