# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_auto_20170524_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='owner',
        ),
    ]
