# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_remove_booking_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_inward_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_outward_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
    ]
