# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-25 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0012_auto_20180425_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvehiclestatus',
            old_name='active',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='vehiclestatus',
            old_name='active',
            new_name='status',
        ),
    ]
