# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0015_auto_20180425_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservice',
            name='name',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
