# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0016_auto_20180426_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehiclepermit',
            name='permit_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehiclestatus',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclepermit',
            name='permit_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiclestatus',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
