# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-27 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_auto_20180417_1922'),
        ('supplier', '0018_auto_20180426_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='serving_states',
            field=models.ManyToManyField(blank=True, to='utils.State'),
        ),
    ]
