# Generated by Django 2.0.2 on 2018-05-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0021_auto_20180513_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='route',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='route',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
