# Generated by Django 2.0.2 on 2018-05-19 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0022_auto_20180514_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='aaho_poc',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'active'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='changed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='services',
            field=models.ManyToManyField(blank=True, limit_choices_to={'deleted': False}, to='supplier.Service'),
        ),
    ]
