# Generated by Django 2.0.5 on 2018-06-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0023_auto_20180519_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='vehicle_number',
            field=models.CharField(db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
