# Generated by Django 2.0.5 on 2019-03-13 01:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0028_auto_20190313_0105'),
        ('supplier', '0027_auto_20180707_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAccountingSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_summary', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAccountingSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_summary', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='driverphone',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='driver',
            name='account_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_driver_account', to='utils.Bank'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pan',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='route',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='account_details',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utils.Bank'),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='pan',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='route',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed'), ('semi', 'Semi'), ('half', 'Half'), ('containerized', 'Containerized')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed'), ('semi', 'Semi'), ('half', 'Half'), ('containerized', 'Containerized')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinsurance',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinsurance',
            name='issued_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehiclepermit',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinsurance',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinsurance',
            name='insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.VehicleInsurer'),
        ),
        migrations.AlterField(
            model_name='vehicleinsurance',
            name='issued_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepermit',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleaccountingsummary',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.Vehicle'),
        ),
        migrations.AddField(
            model_name='supplieraccountingsummary',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.Supplier'),
        ),
    ]
