# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0009_bankholidays'),
        ('owner', '0009_auto_20171109_1717'),
        ('driver', '0017_auto_20180101_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=400, null=True)),
                ('pan', models.CharField(blank=True, max_length=15, null=True)),
                ('id_proof', models.CharField(blank=True, max_length=70)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Bank')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Address')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_city', to='utils.City')),
                ('name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('taxation_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.TaxationID')),
            ],
            options={
                'verbose_name_plural': 'Broker Basic Info',
            },
        ),
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('self', 'self'), ('driver', 'driver'), ('owner', 'owner')], default='self', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Bank')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Broker')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Broker')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Broker')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('latest', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('account_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Bank')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_vehicle', to='broker.Broker')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Vehicle')),
            ],
            options={
                'verbose_name_plural': 'Broker Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('document_bearer_type', models.CharField(choices=[('owner', 'owner'), ('driver', 'driver'), ('vehicle', 'vehicle'), ('broker', 'broker')], max_length=50)),
                ('document_bearer_id', models.PositiveIntegerField()),
                ('document_purpose', models.CharField(max_length=100)),
                ('document_type', models.CharField(blank=True, choices=[('PAN', 'PAN Card'), ('DL', 'Driving Licence'), ('EL', 'Election ID'), ('AC', 'Aadhar Card'), ('PT', 'Passport'), ('RC', 'Ration Card'), ('PUC', 'Puc Certificate'), ('FIT', 'Fitness Certificate'), ('REG', 'Registration Certificate'), ('PERM', 'Permission Certificate'), ('INS', 'Insurance Certificate'), ('DEC', 'Declaration')], max_length=100, null=True)),
                ('document_id', models.CharField(blank=True, max_length=100, null=True)),
                ('document', models.CharField(help_text='s3 file key', max_length=255)),
                ('document_thumb', models.CharField(blank=True, help_text='s3 file key', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='brokervehicle',
            unique_together=set([('broker', 'vehicle')]),
        ),
        migrations.AlterUniqueTogether(
            name='brokerowner',
            unique_together=set([('broker', 'owner')]),
        ),
        migrations.AlterUniqueTogether(
            name='brokerdriver',
            unique_together=set([('broker', 'driver')]),
        ),
        migrations.AlterUniqueTogether(
            name='brokeraccount',
            unique_together=set([('broker', 'account')]),
        ),
    ]
