# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-25 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_auto_20180417_1922'),
        ('broker', '0004_auto_20180424_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='aaho_offices',
            field=models.ManyToManyField(blank=True, related_name='broker_aaho_offices', to='utils.AahoOffice'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='aaho_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_aaho_office', to='utils.AahoOffice'),
        ),
    ]
