# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-02 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_remove_broker_aaho_offices'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
