# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_broker_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='active',
        ),
    ]
