# Generated by Django 2.0.5 on 2018-06-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0008_remove_broker_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
