# Generated by Django 2.0.5 on 2018-06-19 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broker', '0010_auto_20180618_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='broker_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='broker_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broker',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='broker_account_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='broker_account_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brokerdriver',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='broker_driver_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brokerdriver',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='broker_driver_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brokerowner',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='broker_owner_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brokerowner',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='broker_owner_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brokervehicle',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='broker_vehicle_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brokervehicle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='broker_vehicle_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='document_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='document_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
