# Generated by Django 2.0.5 on 2018-07-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0011_auto_20180619_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='updated',
        ),
    ]
