# Generated by Django 2.0.5 on 2018-08-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0022_auto_20180622_0213'),
        ('broker', '0012_remove_broker_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='destination_state',
            field=models.ManyToManyField(blank=True, null=True, related_name='broker_destination_states', to='utils.State'),
        ),
    ]
