# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
