# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20180328_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'user', 'verbose_name_plural': 'Profile'},
        ),
    ]
