# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=35, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('phone', models.CharField(blank=True, max_length=35, null=True)),
                ('number_of_truck', models.CharField(blank=True, max_length=35, null=True)),
                ('route', models.CharField(blank=True, max_length=35, null=True)),
                ('other_point_to_be_noted', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Booking Agent',
            },
        ),
        migrations.CreateModel(
            name='BrokerTempData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=35, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_truck_booked_daily', models.CharField(blank=True, max_length=35, null=True)),
                ('owner_base', models.CharField(blank=True, max_length=35, null=True)),
                ('number_of_associated_transporter', models.CharField(blank=True, max_length=35, null=True)),
                ('other_point_to_be_noted', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Broker',
            },
        ),
        migrations.CreateModel(
            name='LoadingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_point', models.CharField(blank=True, max_length=200, null=True)),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Loading point & Material details',
            },
        ),
        migrations.CreateModel(
            name='OthersTempData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=70, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=70, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=70, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=70, null=True)),
                ('designation', models.CharField(blank=True, max_length=70, null=True)),
                ('route', models.CharField(blank=True, max_length=70, null=True)),
                ('number_of_truck', models.CharField(blank=True, max_length=70, null=True)),
                ('other_point_to_be_noted', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Others',
            },
        ),
        migrations.CreateModel(
            name='OwnerTempData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=35, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=35, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=35, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=35, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('designation', models.CharField(blank=True, max_length=35, null=True)),
                ('route', models.CharField(blank=True, max_length=70, null=True)),
                ('rate', models.CharField(blank=True, max_length=70, null=True)),
                ('any_reference', models.CharField(blank=True, max_length=70, null=True)),
                ('other_point_to_be_noted', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Owner',
            },
        ),
        migrations.CreateModel(
            name='TransporterTempData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=70, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=35, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('designation', models.CharField(blank=True, max_length=70, null=True)),
                ('route', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_truck_owned', models.CharField(blank=True, max_length=35, null=True)),
                ('number_booking_done_daily', models.CharField(blank=True, max_length=35, null=True)),
                ('number_of_truck_taken_from_market', models.CharField(blank=True, max_length=35, null=True)),
                ('gps_fitted_vehicle', models.CharField(blank=True, max_length=35, null=True)),
                ('contact_number_of_traffic_person', models.CharField(blank=True, max_length=35, null=True)),
                ('any_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('other_point_to_noted', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Transporter',
            },
        ),
        migrations.CreateModel(
            name='VehicleTempData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=70, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=35, null=True, verbose_name='Driver Name')),
                ('owner_name', models.CharField(blank=True, max_length=35, null=True, verbose_name='Owner Name')),
                ('vehicle_type', models.CharField(blank=True, max_length=70, null=True, verbose_name='Type of Vehicle')),
                ('route', models.CharField(blank=True, max_length=70, null=True)),
                ('owner_num_truck', models.CharField(blank=True, max_length=10, null=True, verbose_name='How many trucks owner have ? ')),
                ('loading_point', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Frequency ( No. of Round trip per month)')),
                ('trip_duration', models.CharField(blank=True, max_length=10, null=True, verbose_name='Time taken per trip (one side)')),
                ('owner_mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Owner Mobile Number')),
                ('rate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rate')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vehicle Number')),
                ('load_provider', models.CharField(blank=True, max_length=70, null=True, verbose_name='')),
                ('driver_mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name=' Who provides load on each side?')),
                ('driver_nature', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nature of driver')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('data_provider', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vehicle Temp Data',
            },
        ),
    ]
