# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletempdata',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicletempdata',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
