# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0010_auto_20170301_1958'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0030_auto_20170426_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='PODFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('lr_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_files', to='team.LrNumber')),
                ('s3_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_pod', to='api.S3Upload')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='podfile',
            unique_together=set([('lr_number', 'serial')]),
        ),
    ]
