# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_auto_20171004_2026'),
        ('api', '0012_auto_20170513_1130'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_files', to='owner.Owner')),
                ('s3_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_owner', to='api.S3Upload')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('s3_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_vehicle', to='api.S3Upload')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_files', to='owner.Vehicle')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vehiclefile',
            unique_together=set([('vehicle', 'serial')]),
        ),
        migrations.AlterUniqueTogether(
            name='ownerfile',
            unique_together=set([('owner', 'serial')]),
        ),
    ]
