# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_auto_20170914_1333'),
        ('api', '0012_auto_20170513_1130'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileupload', '0002_auto_20171006_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_category', models.CharField(choices=[(b'PAN', b'PAN Card'), (b'DL', b'Driving Licence'), (b'EL', b'Election ID'), (b'AC', b'Aadhar Card'), (b'PT', b'Passport'), (b'RC', b'Ration Card')], max_length=70, null=True)),
                ('serial', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_files', to='driver.Driver')),
                ('s3_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_driver', to='api.S3Upload')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ownerfile',
            name='document_category',
            field=models.CharField(choices=[(b'PAN', b'PAN Card'), (b'DL', b'Driving Licence'), (b'EL', b'Election ID'), (b'AC', b'Aadhar Card'), (b'PT', b'Passport'), (b'RC', b'Ration Card'), (b'DEC', b'Declaration')], max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='vehiclefile',
            name='document_category',
            field=models.CharField(choices=[(b'PUC', b'Puc Certificate'), (b'FIT', b'Fitness Certificate'), (b'REG', b'Registration Certificate'), (b'PERM', b'Permission Certificate'), (b'INS', b'Insurance Certificate')], max_length=70, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='driverfile',
            unique_together=set([('driver', 'serial')]),
        ),
    ]
