# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0011_auto_20171226_1602'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20171026_1726'),
        ('fileupload', '0003_auto_20171006_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=300, null=True)),
                ('serial', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheque_files', to='sme.Sme')),
                ('s3_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_files', to='api.S3Upload')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='chequefile',
            unique_together=set([('customer_name', 'serial')]),
        ),
    ]
