# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_auto_20180105_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequefile',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chequefile',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
