# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_auto_20180105_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequefile',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
