# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_chequefile_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequefile',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
    ]
