# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileupload', '0007_chequefile_payment_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequefile',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileupload_cheque_resolved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chequefile',
            name='resolved_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chequefile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileupload_cheque_uploaded_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
