# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0008_auto_20180109_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chequefile',
            old_name='payment_received',
            new_name='resolved',
        ),
    ]
