# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0009_auto_20180109_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequefile',
            name='cheque_date',
            field=models.DateField(null=True),
        ),
    ]
