# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0066_auto_20180214_1658'),
        ('fileupload', '0010_chequefile_cheque_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='podfile',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.ManualBooking'),
        ),
    ]
