# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0010_chequefile_cheque_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverfile',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podfile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
