# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0012_auto_20180215_1946'),
        ('fileupload', '0011_auto_20180216_1510'),
    ]

    operations = [
    ]
