# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0014_auto_20180222_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverfile',
            name='s3_thumb_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ownerfile',
            name='s3_thumb_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehiclefile',
            name='s3_thumb_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
