# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-22 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0015_auto_20180222_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverfile',
            old_name='resolved',
            new_name='verified',
        ),
        migrations.AddField(
            model_name='ownerfile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclefile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
