# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0016_auto_20180222_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='podfile',
            name='s3_thumb_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='podfile',
            name='s3_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
