# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0018_invoicereceiptfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicereceiptfile',
            old_name='tbb_invoice_receipt',
            new_name='invoice_receipt',
        ),
        migrations.RemoveField(
            model_name='invoicereceiptfile',
            name='to_pay_invoice_receipt',
        ),
    ]
