# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileupload', '0020_podfile_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='podfile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pod_file_verified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podfile',
            name='verified_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pod_file_uploaded_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
