# Generated by Django 2.0.5 on 2018-06-19 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileupload', '0022_auto_20180513_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequefile',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheque_file_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chequefile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheque_file_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chequefile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chequefile',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverfile',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_file_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverfile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_file_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverfile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverfile',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicereceiptfile',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_receipt_file_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicereceiptfile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_receipt_file_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicereceiptfile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicereceiptfile',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerfile',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_file_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerfile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_file_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerfile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerfile',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podfile',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pod_file_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podfile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pod_file_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podfile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podfile',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclefile',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_file_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclefile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_file_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclefile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclefile',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
