# Generated by Django 2.0.5 on 2018-11-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0026_auto_20181015_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicereceiptfile',
            name='invoice_confirm_mode',
            field=models.CharField(choices=[('PH', 'Phone'), ('WA', 'Written Acknowledgement'), ('EM', 'Email Screenshot')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='invoicereceiptfile',
            name='s3_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_invoice_receipt', to='api.S3Upload'),
        ),
    ]
