# Generated by Django 2.0.5 on 2019-01-29 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0131_auto_20181220_1224'),
        ('api', '0017_remove_s3upload_deleted_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileupload', '0027_auto_20181101_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeighingSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_url', models.URLField(blank=True, null=True, unique=True)),
                ('s3_thumb_url', models.URLField(blank=True, null=True, unique=True)),
                ('serial', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('verified_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.ManualBooking')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weighing_slip_file_changed_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weighing_slip_file_created_by', to=settings.AUTH_USER_MODEL)),
                ('s3_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_weighing_slip', to='api.S3Upload')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weighing_slip_uploaded_by', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weighing_slip_file_verified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
