# Generated by Django 2.0.5 on 2019-03-13 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0028_auto_20190313_0105'),
        ('fileupload', '0028_weighingslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverfile',
            name='supplier_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_driver_files', to='supplier.Driver'),
        ),
        migrations.AddField(
            model_name='ownerfile',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_files', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='vehiclefile',
            name='supplier_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_vehicle_files', to='supplier.Vehicle'),
        ),
        migrations.AlterField(
            model_name='driverfile',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_files', to='driver.Driver'),
        ),
        migrations.AlterField(
            model_name='ownerfile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_files', to='owner.Owner'),
        ),
        migrations.AlterField(
            model_name='vehiclefile',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_files', to='owner.Vehicle'),
        ),
    ]
