# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 01:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0003_auto_20170216_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservendor',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='uservendor',
            unique_together=set([('user', 'phone')]),
        ),
    ]
