# Generated by Django 2.0.2 on 2018-05-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20180517_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='is_insured',
            field=models.CharField(blank=True, choices=[('no', 'NO'), ('yes', 'YES')], max_length=4, null=True),
        ),
    ]
