# Generated by Django 2.0.2 on 2018-05-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20180519_0041'),
        ('transaction', '0008_auto_20180517_1954'),
    ]

    operations = [
    ]
