# Generated by Django 2.0 on 2018-05-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_merge_20180519_1250'),
        ('transaction', '0007_auto_20180516_1537'),
    ]

    operations = [
    ]
