# Generated by Django 2.0 on 2018-05-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20180523_1921'),
        ('transaction', '0014_auto_20180524_1713'),
    ]

    operations = [
    ]
