# Generated by Django 2.0.5 on 2018-06-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0017_auto_20180608_1928'),
        ('transaction', '0019_auto_20180607_1917'),
    ]

    operations = [
    ]
