# Generated by Django 2.0.5 on 2018-06-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0021_auto_20180614_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='is_insured',
            field=models.CharField(blank=True, choices=[('no', 'NO'), ('yes', 'YES')], max_length=4, null=True),
        ),
    ]
