# Generated by Django 2.0.5 on 2018-06-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0030_auto_20180622_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='is_insured',
        ),
    ]
