from team.models import DataTablesFilter


def filter_data():
    data = []
    for row in DataTablesFilter.objects.all():
        data.append({
            'id': row.id,
            'criteria': row.criteria
        })
    return data


def update_filter_data():
    data = [{'id': 4,
             'criteria': [{'field_name': 'payment_date_between',
                           'input_type': 'date',
                           'placeholder': 'Choose Date',
                           'display_name': 'Payment Date'},
                          {'url': '/api/multichoice-filter-list/?filter_key=inward_payment_mode_choices',
                           'data_parse': 'id:value.key?text:value.value',
                           'field_name': 'payment_mode',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Payment Mode',
                           'display_name': 'Payment Mode'},
                          {'url': '/api/tiny-manual-booking-list/',
                           'data_parse': 'id:value.id?text:value.booking_id',
                           'field_name': 'booking',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Booking',
                           'display_name': 'Booking'},
                          {'url': '/api/team-lr-number-list/',
                           'data_parse': 'id: value.id? text: value.lr_number',
                           'field_name': 'lr_number',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Lr Number',
                           'display_name': 'Lr Number'},
                          {'field_name': 'received_from',
                           'input_type': 'text',
                           'placeholder': 'Received From',
                           'display_name': 'Received From'},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'actual_amount_range',
                           'input_type': 'number',
                           'placeholder': 'Amount',
                           'display_name': 'Amount'},
                          {'field_name': 'invoice_number',
                           'input_type': 'text',
                           'placeholder': 'Invoice Number',
                           'display_name': 'Invoice Number'},
                          {'field_name': 'trn',
                           'input_type': 'text',
                           'placeholder': 'TRN',
                           'display_name': 'TRN'},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'id_range',
                           'input_type': 'number',
                           'placeholder': 'ID',
                           'display_name': 'ID'},
                          {'url': '/api/owner-owner-vehicle-list/',
                           'data_parse': 'id: value.id? text: value.vehicle_number_display',
                           'field_name': 'vehicle_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Vehicle',
                           'display_name': 'Vehicle'}]},
            {'id': 14,
             'criteria': [{'field_name': 'id_range',
                           'input_type': 'number',
                           'placeholder': 'ID',
                           'display_name': 'ID'},
                          {'field_name': 'lr_number',
                           'input_type': 'text',
                           'placeholder': 'LR Number',
                           'display_name': 'LR Number'},
                          {'url': '/api/tiny-manual-booking-list/',
                           'data_parse': 'id:value.id?text:value.booking_id',
                           'field_name': 'booking',
                           'input_type': 'select',
                           'placeholder': 'Select Booking',
                           'display_name': 'Booking'},
                          {'field_name': 'datetime_between',
                           'input_type': 'date',
                           'placeholder': 'Choose Date',
                           'display_name': 'LR Date'}]},
            {'id': 7,
             'criteria': [{'url': '/api/owner-owner-vehicle-list/',
                           'data_parse': 'id: value.id? text: value.vehicle_number_display',
                           'field_name': 'vehicle_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Vehicle',
                           'display_name': 'Vehicle'},
                          {'field_name': 'owner_name',
                           'input_type': 'text',
                           'placeholder': 'Owner Name',
                           'display_name': 'Owner Name'},
                          {'field_name': 'owner_phone',
                           'input_type': 'text',
                           'placeholder': 'Owner Phone',
                           'display_name': 'Owner Phone'},
                          {'field_name': 'id_range',
                           'input_type': 'number',
                           'placeholder': 'ID',
                           'display_name': 'ID'}]},
            {'id': 11,
             'criteria': [{'field_name': 'id_range',
                           'input_type': 'number',
                           'placeholder': 'ID',
                           'display_name': 'ID'},
                          {'field_name': 'ref_number',
                           'input_type': 'text',
                           'placeholder': 'Reference Number',
                           'display_name': 'Reference Number'},
                          {'url': '/api/tiny-manual-booking-list/',
                           'data_parse': 'id:value.id?text:value.booking_id',
                           'field_name': 'booking',
                           'input_type': 'select',
                           'placeholder': 'Select Booking',
                           'display_name': 'Booking'},
                          {'url': '/api/team-lr-number-list/',
                           'data_parse': 'id: value.id? text: value.lr_number',
                           'field_name': 'lr_number',
                           'input_type': 'select',
                           'placeholder': 'Select Lr Number',
                           'display_name': 'Lr Number'},
                          {'field_name': 'datetime_between',
                           'input_type': 'date',
                           'placeholder': 'Choose Date',
                           'display_name': 'Created Date'}]},
            {'id': 12,
             'criteria': [{'field_name': 'id_range',
                           'input_type': 'number',
                           'placeholder': 'ID',
                           'display_name': 'ID'},
                          {'options': [{'text': 'Yes', 'value': True},
                                       {'text': 'No', 'value': False}],
                           'field_name': 'verified',
                           'input_type': 'choices',
                           'placeholder': 'Select Verified Status',
                           'display_name': 'Is Verified'},
                          {'options': [{'text': 'Yes', 'value': True},
                                       {'text': 'No', 'value': False}],
                           'field_name': 'is_valid',
                           'input_type': 'choices',
                           'placeholder': 'Select Valid Status',
                           'display_name': 'Is Valid'},
                          {'url': '/api/team-lr-number-list/',
                           'data_parse': 'id: value.id? text: value.lr_number',
                           'field_name': 'lr_number',
                           'input_type': 'select',
                           'placeholder': 'Select Lr Number',
                           'display_name': 'Lr Number'},
                          {'url': '/api/tiny-manual-booking-list/',
                           'data_parse': 'id:value.id?text:value.booking_id',
                           'field_name': 'booking',
                           'input_type': 'select',
                           'placeholder': 'Select Booking',
                           'display_name': 'Booking'},
                          {'field_name': 'datetime_between',
                           'input_type': 'date',
                           'placeholder': 'Choose Date',
                           'display_name': 'Created Date'}]},
            {'id': 9,
             'criteria': [{'field_name': 'name',
                           'input_type': 'text',
                           'placeholder': 'Driver Name',
                           'display_name': 'Driver Name'},
                          {'field_name': 'phone',
                           'input_type': 'text',
                           'placeholder': 'Driver Phone',
                           'display_name': 'Driver Phone'},
                          {'field_name': 'driving_licence_number',
                           'input_type': 'text',
                           'placeholder': 'Drivering Licence Number',
                           'display_name': 'Drivering Licence Number'}]},
            {'id': 8,
             'criteria': [{'field_name': 'vehicle_number',
                           'input_type': 'text',
                           'placeholder': 'vehicle Number',
                           'display_name': 'vehicle Number'},
                          {'url': '/api/supplier-supplier-list/',
                           'data_parse': "id: value.id? text: value.owner_profile.name + ',' + value.owner_profile.phone",
                           'field_name': 'owner',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Owner',
                           'display_name': 'Owner'},
                          {'url': '/api/supplier-supplier-driver-list/',
                           'data_parse': "id: value.id? text: value.name + ' ' + value.phone",
                           'field_name': 'driver',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Driver',
                           'display_name': 'Driver'},
                          {'url': '/api/supplier-vehicle-category-list/',
                           'data_parse': 'id: value.id? text: value.vehicle_type',
                           'field_name': 'vehicle_type',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Vehicle Category',
                           'display_name': 'Vehicle Category'}]},
            {'id': 10,
             'criteria': [{'field_name': 'id_range',
                           'input_type': 'number',
                           'placeholder': 'ID',
                           'display_name': 'ID'},
                          {'field_name': 'account_holder_name',
                           'input_type': 'text',
                           'placeholder': 'Beneficiary Name',
                           'display_name': 'Beneficiary Name'},
                          {'field_name': 'beneficiary_code',
                           'input_type': 'text',
                           'placeholder': 'Beneficiary Code',
                           'display_name': 'Beneficiary Code'},
                          {'field_name': 'account_number',
                           'input_type': 'text',
                           'placeholder': 'Account Number',
                           'display_name': 'Account Number'},
                          {'field_name': 'ifsc',
                           'input_type': 'text',
                           'placeholder': 'IFSC',
                           'display_name': 'IFSC'},
                          {'field_name': 'bank',
                           'input_type': 'text',
                           'placeholder': 'Bank Name',
                           'display_name': 'Bank Name'},
                          {'options': [{'text': 'Saving Account', 'value': 'SA'},
                                       {'text': 'Current Account', 'value': 'CA'},
                                       {'text': 'Kisan Credit Card', 'value': 'KCC'},
                                       {'text': 'Recurring Account', 'value': 'RA'}],
                           'field_name': 'account_type',
                           'input_type': 'choices',
                           'placeholder': 'Select Account Type',
                           'display_name': 'Account Type'},
                          {'options': [{'text': 'NEFT', 'value': 'neft'},
                                       {'text': 'RTGS', 'value': 'rtgs'},
                                       {'text': 'Both', 'value': 'both'},
                                       {'text': 'HDFC Internal Account', 'value': 'hdfc_internal_account'}],
                           'field_name': 'transaction_type',
                           'input_type': 'choices',
                           'placeholder': 'Select Transaction Type',
                           'display_name': 'Transaction Type'},
                          {'options': [{'text': 'Yes', 'value': 'yes'},
                                       {'text': 'No', 'value': 'no'}],
                           'field_name': 'is_verified',
                           'input_type': 'choices',
                           'placeholder': 'Select Is Verified',
                           'display_name': 'Is Verified'},
                          {'field_name': 'created_between',
                           'input_type': 'date',
                           'placeholder': 'Choose Date',
                           'display_name': 'Created Date'}]},
            {'id': 13,
             'criteria': [{'field_name': 'id_range',
                           'input_type': 'number',
                           'placeholder': 'ID',
                           'display_name': 'ID'},
                          {'field_name': 'bill_number',
                           'input_type': 'text',
                           'placeholder': 'Bill Number',
                           'display_name': 'Bill Number'},
                          {'url': '/api/team-lr-number-list/',
                           'data_parse': 'id: value.id? text: value.lr_number',
                           'field_name': 'lr_number',
                           'input_type': 'select',
                           'placeholder': 'Select Lr Number',
                           'display_name': 'Lr Number'},
                          {'url': '/api/tiny-manual-booking-list/',
                           'data_parse': 'id:value.id?text:value.booking_id',
                           'field_name': 'booking',
                           'input_type': 'select',
                           'placeholder': 'Select Booking',
                           'display_name': 'Booking'},
                          {'field_name': 'bill_date_between',
                           'input_type': 'date',
                           'placeholder': 'Choose Date',
                           'display_name': 'Biiled Date'}]},
            {'id': 15,
             'criteria': [{'field_name': 'id_range',
                           'input_type': 'number',
                           'placeholder': 'ID',
                           'display_name': 'ID'},
                          {'field_name': 'device_id',
                           'input_type': 'text',
                           'placeholder': 'Device ID',
                           'display_name': 'Device ID'},
                          {'url': '/api/driver-driver-list/',
                           'data_parse': "id: value.id? text: value.name + ' ' + value.phone",
                           'field_name': 'driver',
                           'input_type': 'select',
                           'placeholder': 'Select Driver',
                           'display_name': 'Driver'},
                          {'url': '/api/owner-owner-vehicle-list/',
                           'data_parse': 'id: value.id? text: value.vehicle_number_display',
                           'field_name': 'vehicle',
                           'input_type': 'select',
                           'placeholder': 'Select Vehicle',
                           'display_name': 'Vehicle'},
                          {'url': '/api/driver-gps-device-provider-list/',
                           'data_parse': 'id: value.id? text: value.name',
                           'field_name': 'gps_device_provider',
                           'input_type': 'select',
                           'placeholder': 'Select GPS Provider',
                           'display_name': 'GPS Provider'},
                          {'field_name': 'location_time_between',
                           'input_type': 'date',
                           'placeholder': 'Choose Date',
                           'display_name': 'Location Time'}]},
            {'id': 2,
             'criteria': [{'url': '/api/sme-sme-list/',
                           'data_parse': "id:value.id?text:value.sme_profile.name + ' ,' + value.company_code",
                           'field_name': 'customer',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Customer',
                           'display_name': 'Customer'},
                          {'field_name': 'invoice_number',
                           'input_type': 'text',
                           'placeholder': 'Invoice Number',
                           'display_name': 'Invoice Number'},
                          {'url': '/api/tiny-manual-booking-list/',
                           'data_parse': 'id:value.id?text:value.booking_id',
                           'field_name': 'booking',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Booking',
                           'display_name': 'Booking'},
                          {'url': '/api/team-lr-number-list/',
                           'data_parse': 'id: value.id? text: value.lr_number',
                           'field_name': 'lr_number',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Lr Number',
                           'display_name': 'Lr Number'},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'id_range',
                           'input_type': 'number',
                           'placeholder': 'ID',
                           'display_name': 'ID'},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'total_amount_range',
                           'input_type': 'number',
                           'placeholder': 'Amount',
                           'display_name': 'Amount'},
                          {'field_name': 'date_between',
                           'input_type': 'date',
                           'placeholder': 'Choose Date',
                           'display_name': 'Invoice Date'}]},
            {'id': 3,
             'criteria': [{'field_name': 'payment_date_between',
                           'input_type': 'date',
                           'placeholder': 'Choose Date',
                           'display_name': 'Payment Date'},
                          {'url': '/api/multichoice-filter-list/?filter_key=outward_payment_status_choices',
                           'data_parse': 'id:value.key?text:value.value',
                           'field_name': 'status',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Outward Payment Status',
                           'display_name': 'Status'},
                          {'url': '/api/multichoice-filter-list/?filter_key=outward_payment_mode_choices',
                           'data_parse': 'id:value.key?text:value.value',
                           'field_name': 'payment_mode',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Payment Mode',
                           'display_name': 'Payment Mode'},
                          {'field_name': 'paid_to',
                           'input_type': 'text',
                           'placeholder': 'Paid To',
                           'display_name': 'Paid To'},
                          {'url': '/api/tiny-manual-booking-list/',
                           'data_parse': 'id:value.id?text:value.booking_id',
                           'field_name': 'booking',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Booking',
                           'display_name': 'Booking'},
                          {'url': '/api/team-lr-number-list/',
                           'data_parse': 'id: value.id? text: value.lr_number',
                           'field_name': 'lr_number',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Lr Number',
                           'display_name': 'Lr Number'},
                          {'url': '/api/owner-fuel-card-list/',
                           'data_parse': 'id: value.id? text: value.text',
                           'field_name': 'fuel_card',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Card Number',
                           'display_name': 'Fuel Card'},
                          {'url': '/api/utils-bank-list/',
                           'data_parse': "id: value.id? text: value.account_number+', '+value.account_holder_name",
                           'field_name': 'bank_account',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Account Number',
                           'display_name': 'Bank Account'},
                          {'options': [{'text': 'Yes', 'value': True},
                                       {'text': 'No', 'value': False}],
                           'field_name': 'is_refund_amount',
                           'input_type': 'choices',
                           'placeholder': 'Select Is Refund Amount',
                           'display_name': 'Is Refund Payment'},
                          {'url': '/api/owner-owner-vehicle-list/',
                           'data_parse': 'id: value.id? text: value.vehicle_number_display',
                           'field_name': 'vehicle_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Vehicle',
                           'display_name': 'Vehicle'},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'id_range',
                           'input_type': 'number',
                           'placeholder': 'ID',
                           'display_name': 'ID'},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'actual_amount_range',
                           'input_type': 'number',
                           'placeholder': 'Amount',
                           'display_name': 'Amount'},
                          {'field_name': 'utr',
                           'input_type': 'text',
                           'placeholder': 'UTR',
                           'display_name': 'UTR'}]},
            {'id': 5,
             'criteria': [{'url': '/api/utils-aaho-office-list/',
                           'data_parse': 'id: value.id?text: value.branch_name',
                           'field_name': 'aaho_office',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Aaho Office',
                           'display_name': 'Aaho Office'},
                          {'url': '/api/employee-list/',
                           'data_parse': 'id: value.id?text: value.emp_name',
                           'field_name': 'aaho_poc',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Aaho POC',
                           'display_name': 'Aaho POC'},
                          {'field_name': 'company_code',
                           'input_type': 'text',
                           'placeholder': 'Company Code',
                           'display_name': 'Company Code'},
                          {'field_name': 'company_name',
                           'input_type': 'text',
                           'placeholder': 'Company Name',
                           'display_name': 'Company Name'},
                          {'field_name': 'gstin',
                           'input_type': 'text',
                           'placeholder': 'GSTIN',
                           'display_name': 'GSTIN'},
                          {'field_name': 'id_range',
                           'input_type': 'number',
                           'placeholder': 'ID',
                           'display_name': 'ID'}]},
            {'id': 16,
             'criteria': [{'field_name': 'shipment_date_between',
                           'input_type': 'date',
                           'placeholder': 'Choose Date',
                           'display_name': 'Shipment Date'},
                          {'url': '/api/team-lr-number-list/',
                           'data_parse': 'id: value.id? text: value.lr_number',
                           'field_name': 'lr_number',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Lr Number',
                           'display_name': 'Lr Number'},
                          {'url': '/api/owner-owner-vehicle-list/',
                           'data_parse': 'id: value.id? text: value.vehicle_number_display',
                           'field_name': 'vehicle_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Vehicle',
                           'display_name': 'Vehicle'},
                          {'url': '/api/utils-city-list/',
                           'data_parse': "id: value.id? text: value.name + ',' + value.code + ',' + value.state.name",
                           'field_name': 'to_city_fk_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select To City',
                           'display_name': 'To City'},
                          {'url': '/api/utils-city-list/',
                           'data_parse': "id: value.id? text: value.name + ',' + value.code + ',' + value.state.name",
                           'field_name': 'from_city_fk_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select From City',
                           'display_name': 'From City'}]},
            {'id': 6,
             'criteria': [{'field_name': 'name',
                           'input_type': 'text',
                           'placeholder': 'Supplier Name',
                           'display_name': 'Supplier Name'},
                          {'field_name': 'phone',
                           'input_type': 'text',
                           'placeholder': 'Supplier Phone',
                           'display_name': 'Supplier Phone'},
                          {'url': '/api/utils-aaho-office-list/',
                           'data_parse': 'id: value.id?text: value.branch_name',
                           'field_name': 'aaho_office',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Aaho Office',
                           'display_name': 'Aaho Office'},
                          {'url': '/api/supplier-vehicle-list/',
                           'data_parse': 'id: value.id? text: value.vehicle_number_display',
                           'field_name': 'vehicle_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Vehicle',
                           'display_name': 'Vehicle'},
                          {'url': '/api/employee-list/',
                           'data_parse': 'id: value.id?text: value.emp_name',
                           'field_name': 'aaho_poc',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Aaho POC',
                           'display_name': 'Aaho POC'},
                          {'field_name': 'code',
                           'input_type': 'text',
                           'placeholder': 'Supplier Code',
                           'display_name': 'Supplier Code'},
                          {'field_name': 'pan',
                           'input_type': 'text',
                           'placeholder': 'Supplier PAN',
                           'display_name': 'Supplier PAN'}]},
            {'id': 1,
             'criteria': [{'url': '/api/sme-sme-list/',
                           'data_parse': "id:value.id?text:value.sme_profile.name + ' ,' + value.company_code",
                           'field_name': 'company_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Customer Who Placed Order',
                           'display_name': 'Customer Who Placed Order'},
                          {'url': '/api/sme-sme-list/',
                           'data_parse': "id:value.id?text:value.sme_profile.name + ' ,' + value.company_code",
                           'field_name': 'customer_to_be_billed_to_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Customer Who will Make Payment',
                           'display_name': 'Customer Who will Make Payment'},
                          {'url': '/api/supplier-supplier-list/',
                           'data_parse': "id: value.id? text: value.name + ' ' + value.phone",
                           'field_name': 'accounting_supplier_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Accounting Supplier',
                           'display_name': 'Accounting Supplier'},
                          {'url': '/api/supplier-supplier-list/',
                           'data_parse': "id: value.id? text: value.name + ' ' + value.phone",
                           'field_name': 'booking_supplier_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Booking Supplier',
                           'display_name': 'Booking Supplier'},
                          {'url': '/api/supplier-supplier-list/',
                           'data_parse': "id: value.id? text: value.name + ' ' + value.phone",
                           'field_name': 'owner_supplier_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Owner',
                           'display_name': 'Owner'},
                          {'url': '/api/supplier-vehicle-list/',
                           'data_parse': 'id: value.id? text: value.vehicle_number_display',
                           'field_name': 'vehicle_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Vehicle',
                           'display_name': 'Vehicle'},
                          {'url': '/api/team-lr-number-list/',
                           'data_parse': 'id: value.id? text: value.lr_number',
                           'field_name': 'lr_number',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Lr Number',
                           'display_name': 'Lr Number'},
                          {'field_name': 'shipment_date_between',
                           'input_type': 'date',
                           'placeholder': 'Choose Date',
                           'display_name': 'Shipment Date'},
                          {'url': '/api/multichoice-filter-list/?filter_key=booking_inward_payment_status_choices',
                           'data_parse': 'id:value.key?text:value.value',
                           'field_name': 'inward_payment_status',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Inward Payment Status',
                           'display_name': 'Inward Payment Status'},
                          {'url': '/api/multichoice-filter-list/?filter_key=booking_outward_payment_status_choices',
                           'data_parse': 'id:value.key?text:value.value',
                           'field_name': 'outward_payment_status',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Outward Payment Status',
                           'display_name': 'Outward Payment Status'},
                          {'url': '/api/multichoice-filter-list/?filter_key=booking_invoice_status_choices',
                           'data_parse': 'id:value.key?text:value.value',
                           'field_name': 'invoice_status',
                           'input_type': 'multiselect',
                           'placeholder': 'Invoice Status',
                           'display_name': 'Invoice Status'},
                          {'url': '/api/multichoice-filter-list/?filter_key=booking_pod_status_choices',
                           'data_parse': 'id:value.key?text:value.value',
                           'field_name': 'pod_status',
                           'input_type': 'multiselect',
                           'placeholder': 'Select POD Status',
                           'display_name': 'POD Status'},
                          {'url': '/api/utils-aaho-office-list/',
                           'data_parse': 'id: value.id? text: value.branch_name',
                           'field_name': 'source_office_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Source Office',
                           'display_name': 'Source Office'},
                          {'url': '/api/utils-aaho-office-list/',
                           'data_parse': 'id: value.id?text: value.branch_name',
                           'field_name': 'destination_office_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Destination Office',
                           'display_name': 'Destination Office'},
                          {'url': '/api/utils-city-list/',
                           'data_parse': "id: value.id? text: value.name + ',' + value.code + ',' + value.state.name",
                           'field_name': 'to_city_fk_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select To City',
                           'display_name': 'To City'},
                          {'url': '/api/utils-city-list/',
                           'data_parse': "id: value.id? text: value.name + ',' + value.code + ',' + value.state.name",
                           'field_name': 'from_city_fk_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select From City',
                           'display_name': 'From City'},
                          {'field_name': 'booking_id',
                           'input_type': 'text',
                           'placeholder': 'Booking ID',
                           'display_name': 'Booking Id'},
                          {'url': '/api/supplier-supplier-driver-list/',
                           'data_parse': "id: value.id? text: value.name + ' ' + value.phone",
                           'field_name': 'driver_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Driver',
                           'display_name': 'Driver'},
                          {'url': '/api/supplier-vehicle-category-list/',
                           'data_parse': 'id: value.id? text: value.vehicle_type',
                           'field_name': 'vehicle_category_id',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Vehicle Category',
                           'display_name': 'Vehicle Category'},
                          {'field_name': 'delivery_datetime_between',
                           'input_type': 'date',
                           'placeholder': 'Choose Date',
                           'display_name': 'Delivered Date'},
                          {'field_name': 'pod_date_between',
                           'input_type': 'date',
                           'placeholder': 'Choose Date',
                           'display_name': 'POD Date'},
                          {'field_name': 'created_between',
                           'input_type': 'date',
                           'placeholder': 'Choose Date',
                           'display_name': 'Created Date'},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'id_range',
                           'input_type': 'number',
                           'placeholder': 'ID',
                           'display_name': 'ID'},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'charged_weight_range',
                           'input_type': 'number',
                           'placeholder': 'Party Charged Weight',
                           'display_name': 'Party Charged Weight'},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'supplier_charged_weight_range',
                           'input_type': 'number',
                           'placeholder': 'Supplier Charged Weight',
                           'display_name': 'Supplier Charged Weight'},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'supplier_rate_range',
                           'input_type': 'number',
                           'placeholder': 'Supplier Rate',
                           'display_name': 'Supplier Rate'},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'total_amount_to_company_range',
                           'input_type': 'number',
                           'placeholder': 'Total Customer Amount',
                           'display_name': "Total Customer's Amount"},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'total_amount_to_owner_range',
                           'input_type': 'number',
                           'placeholder': "Total Owner's Amount",
                           'display_name': "Total Owner's Amount"},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'total_out_ward_amount_range',
                           'input_type': 'number',
                           'placeholder': 'Total Outward Amount',
                           'display_name': 'Total Outward Amount'},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'total_in_ward_amount_range',
                           'input_type': 'number',
                           'placeholder': 'Total Inward Amount',
                           'display_name': 'Total Inward Amount'},
                          {'max': '1000000',
                           'min': '0',
                           'field_name': 'party_rate_range',
                           'input_type': 'number',
                           'placeholder': 'Enter rate',
                           'display_name': 'Party Rate'},
                          {'url': '/api/multichoice-filter-list/?filter_key=booking_billing_type_choices',
                           'data_parse': 'id:value.key?text:value.value',
                           'field_name': 'billing_type',
                           'input_type': 'multiselect',
                           'placeholder': 'Select Billing Type',
                           'display_name': 'Billing Type'}]}]
    for row in data:
        instance = DataTablesFilter.objects.get(id=row['id'])
        instance.criteria = row['criteria']
        instance.save()
