# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-27 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='device_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='token',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
