# Generated by Django 2.0 on 2018-05-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20180513_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='app',
            field=models.CharField(choices=[('AS', 'Aaho Sales'), ('AC', 'Aaho Customer'), ('AO', 'Aaho Owner')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='app',
            field=models.CharField(choices=[('AS', 'Aaho Sales'), ('AC', 'Aaho Customer'), ('AO', 'Aaho Owner')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='device_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='token',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
