# Generated by Django 2.0 on 2018-05-24 11:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0004_auto_20180523_1839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalDevice',
            new_name='HistoricalMobileDevice',
        ),
        migrations.RenameModel(
            old_name='Device',
            new_name='MobileDevice',
        ),
        migrations.AlterModelOptions(
            name='historicalmobiledevice',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical mobile device'},
        ),
    ]
