# Generated by Django 2.0 on 2018-05-24 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20180524_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmobiledevice',
            name='device_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='device_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_devices', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
