# Generated by Django 2.0 on 2018-05-24 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20180524_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
