# Generated by Django 2.0.5 on 2018-06-19 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0007_auto_20180524_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmobiledevice',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_device_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='changed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_device_changed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
