# Generated by Django 2.0.5 on 2018-09-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_auto_20180829_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmobiledevice',
            name='app',
            field=models.CharField(choices=[('AS', 'Aaho Sales'), ('AC', 'Aaho Customer'), ('AO', 'Aaho Owner'), ('AE', 'Aaho Employee'), ('WB', 'Aaho Web')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='app',
            field=models.CharField(choices=[('AS', 'Aaho Sales'), ('AC', 'Aaho Customer'), ('AO', 'Aaho Owner'), ('AE', 'Aaho Employee'), ('WB', 'Aaho Web')], default='AC', max_length=2),
        ),
    ]
