# Generated by Django 2.0.5 on 2018-09-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_auto_20180918_1116'),
        ('notification', '0010_auto_20180918_1126'),
    ]

    operations = [
    ]
