# Generated by Django 2.0.5 on 2018-09-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_merge_20180920_1831'),
        ('notification', '0011_merge_20180918_1233'),
    ]

    operations = [
    ]
