# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('document_bearer_type', models.CharField(choices=[(b'owner', b'owner'), (b'driver', b'driver'), (b'vehicle', b'vehicle'), (b'supplier', b'supplier')], max_length=50)),
                ('document_bearer_id', models.PositiveIntegerField()),
                ('document_purpose', models.CharField(max_length=100)),
                ('document_type', models.CharField(blank=True, choices=[(b'PAN', b'PAN Card'), (b'DL', b'Driving Licence'), (b'EL', b'Election ID'), (b'AC', b'Aadhar Card'), (b'PT', b'Passport'), (b'RC', b'Ration Card'), (b'PUC', b'Puc Certificate'), (b'FIT', b'Fitness Certificate'), (b'REG', b'Registration Certificate'), (b'PERM', b'Permission Certificate'), (b'INS', b'Insurance Certificate'), (b'DEC', b'Declaration')], max_length=100, null=True)),
                ('document_id', models.CharField(blank=True, max_length=100, null=True)),
                ('document', models.CharField(help_text=b's3 file key', max_length=255)),
                ('document_thumb', models.CharField(blank=True, help_text=b's3 file key', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
