# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 22:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_city', models.CharField(blank=True, max_length=35, null=True)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('from_city', models.CharField(blank=True, max_length=35, null=True)),
                ('tonnage', models.CharField(blank=True, max_length=35, null=True)),
                ('no_of_vehicles', models.CharField(blank=True, max_length=35, null=True)),
                ('to_city', models.CharField(blank=True, max_length=35, null=True)),
                ('material', models.CharField(blank=True, max_length=35, null=True)),
                ('type_of_truck', models.CharField(blank=True, max_length=35, null=True)),
                ('rate', models.CharField(blank=True, max_length=35, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
