# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-19 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_auto_20180417_1922'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sme', '0016_sme_lr_format_type'),
        ('fms', '0002_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRequirement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('tonnage', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_vehicles', models.IntegerField(blank=True, default=0, null=True)),
                ('rate', models.IntegerField(blank=True, default=0, null=True)),
                ('material', models.CharField(blank=True, max_length=35, null=True)),
                ('status', models.CharField(choices=[(b'open', b'Open'), (b'cancelled', b'Cancelled'), (b'closed', b'Closed')], default=b'open', max_length=35, null=True)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sme.Sme')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_city', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utils.City')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_city', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utils.City')),
                ('type_of_vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utils.VehicleCategory')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical requirement',
            },
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='requirement_city',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='type_of_truck',
        ),
        migrations.AddField(
            model_name='requirement',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements_placed_by', to='sme.Sme', verbose_name=b'Customer who placed requirement'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[(b'open', b'Open'), (b'cancelled', b'Cancelled'), (b'closed', b'Closed')], default=b'open', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='type_of_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_requirements', to='utils.VehicleCategory', verbose_name=b'Type of Vehicle'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='from_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req_from_city', to='utils.City'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='no_of_vehicles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='to_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req_to_city', to='utils.City'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='tonnage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
