# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-22 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0003_auto_20180419_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrequirement',
            old_name='shipment_date',
            new_name='from_shipment_date',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='shipment_date',
            new_name='from_shipment_date',
        ),
        migrations.AddField(
            model_name='historicalrequirement',
            name='to_shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='to_shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequirement',
            name='material',
            field=models.CharField(default=b'', max_length=35),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='material',
            field=models.CharField(default=b'', max_length=35),
        ),
    ]
