# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-22 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_auto_20180417_1922'),
        ('fms', '0004_auto_20180422_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequirement',
            name='aaho_office',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utils.AahoOffice'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='aaho_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aaho_office', to='utils.AahoOffice'),
        ),
    ]
