# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-24 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0004_auto_20180424_1909'),
        ('fms', '0005_auto_20180422_2253'),
    ]

    operations = [
    ]
