# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0006_merge_20180424_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequirement',
            name='verified',
            field=models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], default=b'N', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='verified',
            field=models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], default=b'N', max_length=35, null=True),
        ),
    ]
