# Generated by Django 2.0.2 on 2018-05-13 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0007_auto_20180505_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.CharField(help_text='s3 file key', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_bearer_type',
            field=models.CharField(choices=[('owner', 'owner'), ('driver', 'driver'), ('vehicle', 'vehicle'), ('supplier', 'supplier')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_thumb',
            field=models.CharField(blank=True, help_text='s3 file key', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, choices=[('PAN', 'PAN Card'), ('DL', 'Driving Licence'), ('EL', 'Election ID'), ('AC', 'Aadhar Card'), ('PT', 'Passport'), ('RC', 'Ration Card'), ('PUC', 'Puc Certificate'), ('FIT', 'Fitness Certificate'), ('REG', 'Registration Certificate'), ('PERM', 'Permission Certificate'), ('INS', 'Insurance Certificate'), ('DEC', 'Declaration')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequirement',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='open', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequirement',
            name='verified',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements_placed_by', to='sme.Sme', verbose_name='Customer who placed requirement'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='open', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='type_of_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_requirements', to='utils.VehicleCategory', verbose_name='Type of Vehicle'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='verified',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=35, null=True),
        ),
    ]
