# Generated by Django 2.0 on 2018-05-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0008_auto_20180513_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequirement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalrequirement',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='verified',
        ),
        migrations.AddField(
            model_name='historicalrequirement',
            name='req_status',
            field=models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled'), ('unverified', 'Unverified'), ('lapsed', 'Lapsed')], default='unverified', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='req_status',
            field=models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled'), ('unverified', 'Unverified'), ('lapsed', 'Lapsed')], default='unverified', max_length=35, null=True),
        ),
    ]
