# Generated by Django 2.0 on 2018-05-22 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fms', '0009_auto_20180516_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppVersions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_platform', models.CharField(choices=[('android', 'Android'), ('ios', 'IOS')], default='android', max_length=15, null=True)),
                ('app_name', models.CharField(choices=[('AS', 'Aaho Sales'), ('AC', 'Aaho Customer'), ('AO', 'Aaho Owner')], default='AO', max_length=15, null=True)),
                ('app_version', models.CharField(max_length=15, null=True)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='androidappversions_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
