# Generated by Django 2.0 on 2018-05-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0010_mobileappversions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappversions',
            name='upgrade_type',
            field=models.CharField(choices=[('force', 'Forcefull'), ('recommend', 'Recommended')], default='recommend', max_length=30, null=True),
        ),
    ]
