# Generated by Django 2.0.5 on 2018-06-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0012_auto_20180607_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequirementquote',
            name='date',
        ),
        migrations.RemoveField(
            model_name='requirementquote',
            name='date',
        ),
    ]
