# Generated by Django 2.0.5 on 2018-06-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0013_auto_20180607_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileappversions',
            name='comment',
            field=models.CharField(default='Latest_version', max_length=100, null=True),
        ),
    ]
