# Generated by Django 2.0.5 on 2018-08-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0015_auto_20180816_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequirement',
            name='remark',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='remark',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
