# Generated by Django 2.0.5 on 2018-09-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0018_auto_20180831_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequirement',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
