# Generated by Django 2.0.5 on 2018-09-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0019_auto_20180906_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileappversions',
            name='app_name',
            field=models.CharField(choices=[('AS', 'Aaho Sales'), ('AC', 'Aaho Customer'), ('AO', 'Aaho Owner'), ('AE', 'Aaho Employee'), ('WB', 'Aaho Web')], default='AO', max_length=15, null=True),
        ),
    ]
