# Generated by Django 2.0.5 on 2018-09-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0020_auto_20180918_1139'),
        ('fms', '0020_auto_20180918_1126'),
    ]

    operations = [
    ]
