# Generated by Django 2.0.5 on 2018-09-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0021_merge_20180918_1233'),
        ('fms', '0021_merge_20180920_1831'),
    ]

    operations = [
    ]
