# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sme',
            name='gstin',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
