# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_aahooffice_branch_name'),
        ('sme', '0003_sme_is_gst_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sme',
            name='address_temp',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sme',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.City'),
        ),
        migrations.AddField(
            model_name='sme',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
