# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0004_auto_20170925_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sme',
            old_name='address_temp',
            new_name='temp_address',
        ),
    ]
