# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0005_auto_20170925_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='is_gst_applicable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
