# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0007_auto_20171006_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sme',
            old_name='temp_address',
            new_name='customer_address',
        ),
    ]
