# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sme', '0010_auto_20171226_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignorconsignee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sme_consignor_consignee_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sme_contact_details_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sme',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sme_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smetaskemail',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
