# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-07 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_auto_20180112_1209'),
        ('sme', '0011_auto_20171226_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, null=True)),
                ('destination', models.CharField(max_length=100, null=True)),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sme.Sme')),
            ],
        ),
        migrations.AddField(
            model_name='contractroute',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sme.CustomerContract'),
        ),
        migrations.AddField(
            model_name='contractroute',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.VehicleCategory'),
        ),
    ]
