# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-11 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0014_auto_20180407_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sme',
            name='latest_transaction_id',
        ),
        migrations.AddField(
            model_name='sme',
            name='latest_lr_serial_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
