# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_auto_20180507_1145'),
        ('sme', '0016_sme_lr_format_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sme',
            name='aaho_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.AahoOffice'),
        ),
    ]
