# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0016_sme_lr_format_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractroute',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalcontractroute',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
