# Generated by Django 2.0.2 on 2018-05-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0017_sme_aaho_office'),
        ('sme', '0017_auto_20180430_1140'),
    ]

    operations = [
    ]
