# Generated by Django 2.0.2 on 2018-05-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0018_merge_20180508_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sme',
            options={'ordering': ['-id'], 'verbose_name_plural': 'SME Basic Info'},
        ),
    ]
