# Generated by Django 2.0.5 on 2018-06-26 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0020_auto_20180619_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
