# Generated by Django 2.0.5 on 2018-06-26 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0022_auto_20180626_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
