# Generated by Django 2.0.5 on 2018-07-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0023_auto_20180626_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='company_code',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
    ]
