# Generated by Django 2.0.5 on 2018-12-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0027_auto_20180821_1919'),
        ('sme', '0027_auto_20181119_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractroute',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='customercontract',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='contractroute',
            unique_together={('contract', 'source', 'destination')},
        ),
    ]
