# Generated by Django 2.0.5 on 2018-06-19 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuslandingpage',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_us_landing_page_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactuslandingpage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_us_landing_page_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactuslandingpage',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactuslandingpage',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrateenquiry',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_rate_enquiry_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyrateenquiry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_rate_enquiry_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyrateenquiry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyrateenquiry',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_form_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_form_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
