# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('fms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('phone', models.CharField(max_length=35, unique=True)),
                ('alt_phone', models.CharField(blank=True, db_index=True, max_length=35, null=True)),
                ('driving_licence_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driving_licence_location', models.CharField(blank=True, max_length=50, null=True)),
                ('driving_licence_validity', models.DateField(blank=True, null=True)),
                ('smartphone_available', models.BooleanField(default=False)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('priority_level', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('account_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Bank')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Address')),
                ('driving_licence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fms.Document')),
                ('id_proof', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.IDDetails')),
                ('taxation_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.TaxationID')),
            ],
            options={
                'verbose_name_plural': 'Driver Basic Info',
            },
        ),
        migrations.CreateModel(
            name='DriverAppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('auth_token', models.CharField(max_length=40, unique=True)),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_number', models.CharField(blank=True, max_length=20, null=True)),
                ('number_verified', models.BooleanField(default=False)),
                ('driving_licence_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_status', models.CharField(choices=[(b'unloaded', b'unloaded'), (b'loading', b'loading'), (b'loaded', b'loaded'), (b'unloading', b'unloading')], default=b'unloaded', max_length=20)),
                ('location_time', models.DateTimeField(null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('inactive_sms_sent_at', models.DateTimeField(null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Driver')),
            ],
            options={
                'db_table': 'driverapp_user',
            },
        ),
        migrations.CreateModel(
            name='GPSLogNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datetime', models.DateTimeField(help_text=b'log time')),
                ('device_id', models.CharField(help_text=b'imei or uuid generated on phone', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('course', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=20, null=True)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('total_memory', models.FloatField(blank=True, null=True)),
                ('available_memory', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('low_memory', models.BooleanField(default=False)),
                ('android_release', models.CharField(blank=True, max_length=20, null=True)),
                ('android_sdk_int', models.IntegerField(blank=True, null=True)),
                ('version_name', models.CharField(blank=True, max_length=20, null=True)),
                ('version_code', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=30, null=True)),
                ('product', models.CharField(blank=True, max_length=30, null=True)),
                ('device', models.CharField(blank=True, max_length=30, null=True)),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_number', models.CharField(blank=True, max_length=20, null=True)),
                ('driving_licence_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_status', models.CharField(blank=True, choices=[(b'unloaded', b'unloaded'), (b'loading', b'loading'), (b'loaded', b'loaded'), (b'unloading', b'unloading')], max_length=20, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_gps_logs', to='driver.DriverAppUser')),
            ],
            options={
                'db_table': 'driverapp_gpslog_new',
                'verbose_name': 'New GPS Log',
                'verbose_name_plural': 'New GPS Logs',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('otp', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gpslognew',
            unique_together=set([('device_id', 'datetime')]),
        ),
    ]
