# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('device_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('sim_number', models.CharField(max_length=20)),
                ('gps_imei', models.CharField(max_length=20)),
                ('gps_id', models.CharField(max_length=20, unique=True)),
                ('vehicle_id', models.CharField(max_length=40, unique=True)),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_number', models.CharField(blank=True, max_length=20, null=True)),
                ('number_verified', models.BooleanField(default=False)),
                ('driving_licence_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_status', models.CharField(choices=[(b'unloaded', b'unloaded'), (b'loading', b'loading'), (b'loaded', b'loaded'), (b'unloading', b'unloading')], default=b'unloaded', max_length=20)),
                ('location_time', models.DateTimeField(null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('inactive_sms_sent_at', models.DateTimeField(null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='GPSDeviceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('location_id', models.CharField(max_length=40, unique=True)),
                ('datetime', models.DateTimeField(help_text=b'log time')),
                ('vehicle_id', models.CharField(help_text=b'imei or uuid generated on phone', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('course', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('engine_on', models.BooleanField(default=False)),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_number', models.CharField(blank=True, max_length=20, null=True)),
                ('driving_licence_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_status', models.CharField(blank=True, choices=[(b'unloaded', b'unloaded'), (b'loading', b'loading'), (b'loaded', b'loaded'), (b'unloading', b'unloading')], max_length=20, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_device_logs', to='driver.GPSDevice')),
            ],
            options={
                'verbose_name': 'GPS Device Log',
                'verbose_name_plural': 'GPS Device Logs',
            },
        ),
        migrations.AlterUniqueTogether(
            name='gpsdevicelog',
            unique_together=set([('vehicle_id', 'datetime')]),
        ),
    ]
