# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20170613_1942'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gpsdevicelog',
            unique_together=set([]),
        ),
    ]
