# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_tracknovategpsdevice_tracknovategpsdevicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracknovategpsdevice',
            name='current_duration',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tracknovategpsdevice',
            name='current_vstatus',
            field=models.TextField(null=True),
        ),
    ]
