# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-01 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_waytrackergpsdevice_waytrackergpsdevicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='alt_phone2',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
