# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_auto_20170914_0144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secugpsdevicelog',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='secugpsdevicelog',
            name='gps_log_id',
        ),
    ]
