# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_auto_20170914_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secugpsdevice',
            name='device_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='secugpsdevicelog',
            name='driver_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
