# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_auto_20170914_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secugpsdevicelog',
            name='driving_licence_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
