# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0013_auto_20171112_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverappuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
