# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0016_auto_20171230_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahindragpsdevicelog',
            options={'verbose_name': 'Mahindra Digisense GPS Device Log', 'verbose_name_plural': 'Mahindra Digisense Device Logs'},
        ),
    ]
