# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0017_auto_20180101_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGPSDevice',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('device_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('sim_number', models.CharField(max_length=20)),
                ('gps_imei', models.CharField(max_length=20)),
                ('gps_id', models.CharField(db_index=True, max_length=20)),
                ('vehicle_id', models.CharField(db_index=True, max_length=40)),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_number', models.CharField(blank=True, max_length=20, null=True)),
                ('number_verified', models.BooleanField(default=False)),
                ('driving_licence_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_status', models.CharField(choices=[(b'unloaded', b'unloaded'), (b'loading', b'loading'), (b'loaded', b'loaded'), (b'unloading', b'unloading')], default=b'unloaded', max_length=20)),
                ('location_time', models.DateTimeField(null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactive_sms_sent_at', models.DateTimeField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='driver.Driver')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical gps device',
            },
        ),
    ]
