# Generated by Django 2.0.5 on 2018-07-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0020_auto_20180619_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevicelog',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gpsdevicelog',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mahindragpsdevicelog',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mahindragpsdevicelog',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secugpsdevicelog',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secugpsdevicelog',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempogogpsdevicelog',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempogogpsdevicelog',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracknovategpsdevicelog',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracknovategpsdevicelog',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waytrackergpsdevicelog',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waytrackergpsdevicelog',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
