# Generated by Django 2.0.5 on 2018-10-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0020_auto_20180905_1312'),
        ('driver', '0023_auto_20180926_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='BharatGPSTrackerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datetime', models.DateTimeField(help_text='log time')),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(max_length=300, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_number', models.CharField(blank=True, max_length=40, null=True)),
                ('driving_licence_number', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_status', models.CharField(blank=True, choices=[('unloaded', 'unloaded'), ('loading', 'loading'), ('loaded', 'loaded'), ('unloading', 'unloading')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Mahindra Digisense GPS Device Log',
                'verbose_name_plural': 'Mahindra Digisense Device Logs',
            },
        ),
        migrations.CreateModel(
            name='GPSDeviceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='gpsdevice',
            name='vehicle_id',
        ),
        migrations.RemoveField(
            model_name='historicalgpsdevice',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=True, to='owner.Vehicle'),
        ),
        migrations.AddField(
            model_name='historicalgpsdevice',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='owner.Vehicle'),
        ),
        migrations.AlterField(
            model_name='gpsdevice',
            name='device_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.GPSDeviceProvider'),
        ),
        migrations.AlterField(
            model_name='historicalgpsdevice',
            name='device_provider',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='driver.GPSDeviceProvider'),
        ),
        migrations.AddField(
            model_name='bharatgpstrackerlog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.GPSDevice'),
        ),
    ]
