# Generated by Django 2.0.5 on 2018-10-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0024_auto_20181015_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bharatgpstrackerlog',
            options={'verbose_name': 'Bharat GPS Device Log', 'verbose_name_plural': 'Bharat Device Logs'},
        ),
        migrations.AddField(
            model_name='bharatgpstrackerlog',
            name='position_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
