# Generated by Django 2.0.5 on 2018-10-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0025_auto_20181016_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsdevice',
            name='gps_id',
        ),
        migrations.RemoveField(
            model_name='gpsdevice',
            name='gps_imei',
        ),
        migrations.RemoveField(
            model_name='gpsdevice',
            name='inactive_sms_sent_at',
        ),
        migrations.RemoveField(
            model_name='gpsdevice',
            name='number_verified',
        ),
        migrations.RemoveField(
            model_name='gpsdevice',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='gpsdevice',
            name='sim_number',
        ),
        migrations.RemoveField(
            model_name='historicalgpsdevice',
            name='gps_id',
        ),
        migrations.RemoveField(
            model_name='historicalgpsdevice',
            name='gps_imei',
        ),
        migrations.RemoveField(
            model_name='historicalgpsdevice',
            name='inactive_sms_sent_at',
        ),
        migrations.RemoveField(
            model_name='historicalgpsdevice',
            name='number_verified',
        ),
        migrations.RemoveField(
            model_name='historicalgpsdevice',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='historicalgpsdevice',
            name='sim_number',
        ),
    ]
