# Generated by Django 2.0.5 on 2018-10-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0026_auto_20181016_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='device_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gpsdevice',
            name='imei',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalgpsdevice',
            name='device_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalgpsdevice',
            name='imei',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
