# Generated by Django 2.0.5 on 2018-10-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0027_auto_20181016_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalgpsdevice',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bharatgpstrackerlog',
            name='position_id',
            field=models.CharField(max_length=35, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gpsdevice',
            name='device_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gpsdevice',
            name='imei',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgpsdevice',
            name='device_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgpsdevice',
            name='imei',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
