# Generated by Django 2.0.5 on 2018-11-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0028_auto_20181017_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpsdevice',
            options={'ordering': ['-id']},
        ),
    ]
