# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_auto_20171003_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='current_city',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel_card_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='sim_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='sim_operator',
        ),
    ]
