# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_bank_status'),
        ('owner', '0008_auto_20171004_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.City'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
