# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_auto_20171109_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='chesis_number',
            new_name='chassis_number',
        ),
    ]
