# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0010_auto_20180112_1209'),
        ('driver', '0018_historicalgpsdevice'),
        ('owner', '0010_auto_20180221_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVehicle',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('vehicle_number', models.CharField(db_index=True, max_length=18)),
                ('rc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('permit', models.CharField(blank=True, max_length=25, null=True)),
                ('permit_validity', models.DateField(blank=True, null=True)),
                ('permit_type', models.CharField(blank=True, max_length=70, null=True)),
                ('vehicle_capacity', models.IntegerField(blank=True, null=True, verbose_name='Exact Vehicle Capacity in Kg')),
                ('body_type', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed'), ('semi', 'Semi'), ('half', 'Half'), ('containerized', 'Containerized')], max_length=50, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=30, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=255, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=255, null=True)),
                ('insurer', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=30, null=True)),
                ('insurance_validity', models.DateField(blank=True, null=True)),
                ('registration_year', models.DateField(blank=True, null=True)),
                ('registration_validity', models.DateField(blank=True, null=True)),
                ('fitness_certificate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('fitness_certificate_issued_on', models.DateField(blank=True, null=True)),
                ('fitness_certificate_validity_date', models.DateField(blank=True, null=True)),
                ('puc_certificate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('puc_certificate_issued_on', models.DateField(blank=True, null=True)),
                ('puc_certificate_validity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'unloaded', b'unloaded'), (b'loading', b'loading'), (b'loaded', b'loaded'), (b'unloading', b'unloading')], default='unloaded', max_length=20)),
                ('gps_enabled', models.BooleanField(default=False)),
                ('update_on', models.DateTimeField(blank=True, editable=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('supplier_name', models.CharField(blank=True, max_length=70, null=True)),
                ('supplier_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=70, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='driver.Driver')),
                ('driver_app_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='driver.DriverAppUser')),
                ('fitness_certificate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fms.Document')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('insurance_certificate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fms.Document')),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='owner.Owner')),
                ('permit_certificate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fms.Document')),
                ('puc_certificate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fms.Document')),
                ('registration_certificate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fms.Document')),
                ('vehicle_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utils.VehicleCategory')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical vehicle',
            },
        ),
    ]
