# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_auto_20180314_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvehicle',
            old_name='update_on',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='update_on',
            new_name='updated_on',
        ),
    ]
