# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-24 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0014_auto_20180316_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={},
        ),
    ]
