# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-02 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0015_auto_20180424_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
