# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0016_auto_20180502_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvehicle',
            name='active',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='active',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='active',
        ),
    ]
