# Generated by Django 2.0.2 on 2018-05-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0017_auto_20180507_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelcard',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Owner Basic Info'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Vehicle Details'},
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='status',
            field=models.CharField(choices=[('unloaded', 'unloaded'), ('loading', 'loading'), ('loaded', 'loaded'), ('unloading', 'unloading')], default='unloaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('unloaded', 'unloaded'), ('loading', 'loading'), ('loaded', 'loaded'), ('unloading', 'unloading')], default='unloaded', max_length=20),
        ),
    ]
