# Generated by Django 2.0.5 on 2018-09-05 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0027_auto_20180821_1919'),
        ('owner', '0019_auto_20180619_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='bank_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utils.Bank'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Bank'),
        ),
    ]
