# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualbooking',
            name='advance_amount_from_company',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='outwardpayment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Not Paid')], default='unpaid', max_length=35, null=True),
        ),
    ]
