# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20170130_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbbinvoice',
            name='advance_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbbinvoice',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
