# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20170131_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outwardpayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT'), ('imps', 'IMPS'), ('rtgs', 'RTGS'), ('happay', 'Happay'), ('fuel_card', 'Fuel Card'), ('hdfc_internal_account', 'HDFC Internal Account')], default='cash', max_length=60, null=True),
        ),
    ]
