# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20170202_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualbooking',
            name='invoice_status',
            field=models.CharField(default='', max_length=35),
        ),
    ]
