# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_manualbooking_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualbooking',
            name='invoice_status',
            field=models.CharField(choices=[('no_invoice', 'No Invoice'), ('invoice_raised', 'Invoice Raised'), ('invoice_sent', 'Invoice Send')], default='no_invoice', max_length=35),
        ),
    ]
