# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20170203_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualbooking',
            name='inward_payment_status',
            field=models.CharField(blank=True, choices=[('no_payment', 'No Payment Received'), ('partial_received', 'Partial Received'), ('full_received', 'Full Received'), ('excess', 'Excess')], max_length=20, null=True),
        ),
    ]
