# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_auto_20170203_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualbooking',
            name='inward_payment_status',
            field=models.CharField(choices=[('no_payment', 'No Payment Received'), ('partial_received', 'Partial Received'), ('full_received', 'Full Received'), ('excess', 'Excess')], default='no_payment', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='outward_payment_status',
            field=models.CharField(choices=[('no_payment_made', 'No Payment Made'), ('partial', 'Partial'), ('complete', 'Complete'), ('excess', 'Excess')], default='no_payment_made', max_length=20, null=True),
        ),
    ]
