# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_auto_20170208_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualbooking',
            name='invoice_status',
            field=models.CharField(choices=[('no_invoice', 'NoInvoice'), ('invoice_raised', 'InvoiceRaised'), ('invoice_sent', 'InvoiceSent')], default='no_invoice', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='inward_payment_status',
            field=models.CharField(choices=[('no_payment', 'Nil'), ('partial_received', 'Partial'), ('full_received', 'Full'), ('excess', 'Excess')], default='no_payment', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='outward_payment_status',
            field=models.CharField(choices=[('no_payment_made', 'Nil'), ('partial', 'Partial'), ('complete', 'Full'), ('excess', 'Excess')], default='no_payment_made', max_length=20, null=True),
        ),
    ]
