# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_auto_20170208_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardpayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT'), ('imps', 'IMPS'), ('rtgs', 'RTGS'), ('happay', 'Happay'), ('hdfc_internal_account', 'HDFC Internal Account')], max_length=60, null=True),
        ),
    ]
