# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_auto_20170210_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lrnumber',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lr_numbers', to='team.ManualBooking'),
        ),
    ]
