# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_auto_20170216_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lrnumber',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_booking', to='team.ManualBooking'),
        ),
    ]
