# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_auto_20170216_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outwardpaymentbill',
            name='bill_number',
            field=models.CharField(editable=False, max_length=30, null=True),
        ),
    ]
