# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-18 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0019_auto_20170218_0315'),
        ('team', '0018_auto_20170216_1917'),
    ]

    operations = [
    ]
