# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_merge_20170218_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardpaymentbill',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outward_payment_bill', to='team.ManualBooking'),
        ),
        migrations.AlterField(
            model_name='lrnumber',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lr_numbers', to='team.ManualBooking'),
        ),
        migrations.AlterField(
            model_name='outwardpaymentbill',
            name='bill_number',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
