# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0025_remove_lrnumber_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualbooking',
            name='supplier_charged_weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=12, null=True, verbose_name='Charged Weight(MT)'),
        ),
    ]
