# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0027_auto_20170307_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardpayment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
