# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0028_inwardpayment_cheque_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='topayinvoice',
            name='bookings',
            field=models.ManyToManyField(null=True, related_name='to_pay_invoices', to='team.ManualBooking'),
        ),
    ]
