# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0029_topayinvoice_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topayinvoice',
            name='bookings',
            field=models.ManyToManyField(related_name='to_pay_invoices', to='team.ManualBooking'),
        ),
    ]
