# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0030_auto_20170426_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissiononlyinvoice',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='ownerreceipt',
            name='booking',
        ),
        migrations.AddField(
            model_name='inwardpayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inward_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lrnumber',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lr_number', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_booking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outwardpayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outward_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outwardpaymentbill',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outward_payment_bill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tbbinvoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tbb_invoice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topayinvoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_pay_invoice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CommissionOnlyInvoice',
        ),
        migrations.DeleteModel(
            name='OwnerReceipt',
        ),
    ]
