# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0031_auto_20170513_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualbooking',
            name='advance_amount_from_company',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='tds_certificate_status',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='N', max_length=20, null=True),
        ),
    ]
