# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0032_auto_20170515_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualbooking',
            name='advance_amount_from_company',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
