# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0035_auto_20170628_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualbooking',
            name='booking_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=70),
        ),
    ]
