# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0002_sme_gstin'),
        ('team', '0036_auto_20170714_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualbooking',
            name='customer_to_be_billed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mb_bill_paid_by', to='sme.Sme'),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mb_bill_order_placed', to='sme.Sme'),
        ),
    ]
