# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0038_auto_20171026_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topayinvoice',
            name='company_address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
