# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0041_auto_20171104_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbbinvoice',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='topayinvoice',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
