# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0042_auto_20171104_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topayinvoice',
            name='booking',
        ),
    ]
