# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_bank_user'),
        ('team', '0045_notifycompletedtaskemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifycompletedtaskemail',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.AahoOffice'),
        ),
    ]
