# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 19:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0046_notifycompletedtaskemail_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('manual_booking', 'Manual Booking'), ('outward_payment', 'Outward Payment'), ('inward_payment', 'Inward Payment'), ('to_pay_invoice', 'To Pay Invoice'), ('tbb_pay_invoice', 'TBB Pay Invoice'), ('outward_payment_bill', 'Outward Payment Bill')], max_length=100)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='notifycompletedtaskemail',
            name='bookings',
            field=models.ManyToManyField(related_name='booking_notify_completed_task', to='team.ManualBooking'),
        ),
    ]
