# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0048_auto_20171127_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteddata',
            name='model',
            field=models.CharField(choices=[('manual_booking', 'Manual Booking'), ('lr_number', 'LR Number'), ('outward_payment', 'Outward Payment'), ('inward_payment', 'Inward Payment'), ('to_pay_invoice', 'To Pay Invoice'), ('tbb_pay_invoice', 'TBB Pay Invoice'), ('outward_payment_bill', 'Outward Payment Bill')], max_length=100),
        ),
    ]
