# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0049_auto_20171204_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='topayinvoice',
            name='advance_payment',
            field=models.IntegerField(default=0),
        ),
    ]
