# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0011_auto_20171226_1602'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0051_auto_20171226_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingInwardPaymentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT'), ('imps', 'IMPS'), ('rtgs', 'RTGS'), ('happay', 'Happay'), ('hdfc_internal_account', 'HDFC Internal Account')], max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('payment_date', models.DateField()),
                ('adjusted_flag', models.BooleanField(default=False)),
                ('uploaded_datetime', models.DateTimeField()),
                ('adjusted_datetime', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_payment_adjusted_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sme.Sme')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_payment_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
