# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0053_auto_20180104_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinginwardpaymententry',
            name='remarks',
        ),
        migrations.AddField(
            model_name='pendinginwardpaymententry',
            name='additional_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendinginwardpaymententry',
            name='bank_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendinginwardpaymententry',
            name='credited_flag',
            field=models.BooleanField(default=False),
        ),
    ]
