# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0055_pendinginwardpaymententry_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginwardpaymententry',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pendinginwardpaymententry',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT'), ('imps', 'IMPS'), ('rtgs', 'RTGS'), ('happay', 'Happay'), ('hdfc_internal_account', 'HDFC')], max_length=50),
        ),
    ]
