# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0056_auto_20180105_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginwardpaymententry',
            name='customer_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
