# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0011_auto_20171226_1602'),
        ('team', '0057_pendinginwardpaymententry_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbbinvoice',
            name='customer_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_tbb_invoice', to='sme.Sme'),
        ),
        migrations.AddField(
            model_name='tbbinvoice',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topayinvoice',
            name='customer_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_to_pay_invoice', to='sme.Sme'),
        ),
        migrations.AddField(
            model_name='topayinvoice',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendinginwardpaymententry',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('hdfc_internal_account', 'HDFC')], max_length=50),
        ),
    ]
