# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0058_auto_20180108_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendinginwardpaymententry',
            old_name='bank_remark',
            new_name='trn',
        ),
    ]
