# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0017_auto_20180101_1421'),
        ('owner', '0009_auto_20171109_1717'),
        ('team', '0059_auto_20180109_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualbooking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Driver'),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.Owner'),
        ),
    ]
