# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
        ('team', '0060_auto_20180110_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualbooking',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_booking_broker', to='broker.Broker'),
        ),
    ]
