# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0061_manualbooking_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinginwardpaymententry',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
