# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0064_auto_20180129_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardpayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT'), ('imps', 'IMPS'), ('rtgs', 'RTGS'), ('happay', 'Happay'), ('cash_deposit', 'Cash Deposit'), ('hdfc_internal_account', 'HDFC Internal Account')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pendinginwardpaymententry',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('cash_deposit', 'Cash Deposit'), ('hdfc_internal_account', 'HDFC')], max_length=50, null=True),
        ),
    ]
