# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_auto_20180112_1209'),
        ('team', '0065_auto_20180207_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='lrnumber',
            name='destination_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lr_destination_office', to='utils.AahoOffice'),
        ),
        migrations.AddField(
            model_name='lrnumber',
            name='source_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lr_source_office', to='utils.AahoOffice'),
        ),
    ]
