# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-24 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0066_auto_20180214_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lrnumber',
            name='source_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lr_source_office', to='utils.AahoOffice'),
        ),
    ]
