# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0067_auto_20180224_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualbooking',
            name='pod_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('unverified', 'Unverified'), ('loading', 'Loading'), ('in_transit', 'In-Transit'), ('unloading', 'Unloading'), ('completed', 'Delivered')], default='pending', max_length=20, null=True),
        ),
    ]
