# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0068_auto_20180301_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lrnumber',
            name='unloading_date',
        ),
        migrations.RemoveField(
            model_name='manualbooking',
            name='consignee_city_fk',
        ),
        migrations.RemoveField(
            model_name='manualbooking',
            name='consignor_city_fk',
        ),
        migrations.RemoveField(
            model_name='manualbooking',
            name='unloading_date',
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=35, null=True, unique=True, verbose_name='Booking ID'),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mb_bill_order_placed', to='sme.Sme', verbose_name='Customer who has placed order '),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='company_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Code'),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='customer_to_be_billed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mb_bill_paid_by', to='sme.Sme', verbose_name='Customer who will make payment'),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='destination_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_office', to='utils.AahoOffice', verbose_name='Destination Office'),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Driver', verbose_name='Driver Name'),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.Owner', verbose_name='Owner Name'),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='source_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_office', to='utils.AahoOffice', verbose_name='Source Office'),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_booking_broker', to='broker.Broker', verbose_name='Broker Name'),
        ),
    ]
