# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0071_auto_20180316_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmanualbooking',
            name='booking_id',
            field=models.CharField(db_index=True, max_length=35, null=True, verbose_name='Booking ID'),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='booking_id',
            field=models.CharField(max_length=35, null=True, unique=True, verbose_name='Booking ID'),
        ),
    ]
