# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0073_auto_20180326_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanualbooking',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmanualbooking',
            name='booking_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=70),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='booking_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=70),
        ),
    ]
