# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0074_auto_20180327_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallrnumber',
            name='invoice_summary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='team.InvoiceSummary'),
        ),
        migrations.AddField(
            model_name='lrnumber',
            name='invoice_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='team.InvoiceSummary'),
        ),
    ]
