# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_s3upload_is_valid'),
        ('team', '0075_auto_20180327_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoicesummary',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalinvoicesummary',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalinvoicesummary',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='invoicesummary',
            name='changed_by',
        ),
        migrations.AddField(
            model_name='invoicesummary',
            name='s3_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.S3Upload'),
        ),
        migrations.DeleteModel(
            name='HistoricalInvoiceSummary',
        ),
    ]
