# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_s3upload_is_valid'),
        ('team', '0079_auto_20180329_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='s3_upload',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.S3Upload'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='s3_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.S3Upload'),
        ),
    ]
