# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0081_auto_20180329_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='summary_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='summary_required',
            field=models.BooleanField(default=False),
        ),
    ]
