# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-03 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0082_auto_20180403_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualbooking',
            name='invoice_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='team.InvoiceSummary'),
        ),
    ]
