# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0085_auto_20180409_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmanualbooking',
            name='pod_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('unverified', 'Unverified'), ('partial_verified', 'Partial Verified'), ('completed', 'Delivered')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='pod_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('unverified', 'Unverified'), ('partial_verified', 'Partial Verified'), ('completed', 'Delivered')], default='pending', max_length=20, null=True),
        ),
    ]
