# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-15 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_auto_20180412_1457'),
        ('team', '0090_auto_20180415_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanualbooking',
            name='from_city_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utils.City'),
        ),
        migrations.AddField(
            model_name='historicalmanualbooking',
            name='to_city_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utils.City'),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='from_city_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_from_city', to='utils.City'),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='to_city_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_to_city', to='utils.City'),
        ),
    ]
