# Generated by Django 2.0.2 on 2018-05-19 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0092_auto_20180513_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinginwardpaymententry',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_payment_adjusted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
