# Generated by Django 2.0.2 on 2018-05-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0092_auto_20180513_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginwardpaymententry',
            name='inward_payment',
            field=models.ManyToManyField(blank=True, to='team.InWardPayment'),
        ),
    ]
