# Generated by Django 2.0.2 on 2018-05-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0093_auto_20180519_0041'),
        ('team', '0093_pendinginwardpaymententry_inward_payment'),
    ]

    operations = [
    ]
