# Generated by Django 2.0.5 on 2018-05-28 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0094_merge_20180519_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outwardpayment',
            name='changed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
