# Generated by Django 2.0.5 on 2018-06-16 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0096_creditdebitnotereason_creditnotecustomer_creditnotecustomerdirectadvance_creditnotesupplier_debitnot'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdebitnotereason',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_debit_note_reason_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditdebitnotereason',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_debit_note_reason_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
