# Generated by Django 2.0.5 on 2018-06-16 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0097_auto_20180616_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditnotesupplier',
            options={'verbose_name_plural': 'Credit Note – Supplier (CNS)'},
        ),
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='adjusted_by',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_adjusted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='approved_by',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='issued_by',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_issued_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
