# Generated by Django 2.0.5 on 2018-06-18 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0098_auto_20180616_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditdebitnotereason',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_adjusted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='bookings',
            field=models.ManyToManyField(blank=True, to='team.ManualBooking', verbose_name='Adjusted Bookings'),
        ),
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='date',
            field=models.DateField(verbose_name='CNC Date'),
        ),
        migrations.AlterField(
            model_name='creditnotecustomerdirectadvance',
            name='date',
            field=models.DateField(verbose_name='CNSA Date'),
        ),
        migrations.AlterField(
            model_name='creditnotesupplier',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_supplier_adjusted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnotesupplier',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_supplier_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnotesupplier',
            name='date',
            field=models.DateField(verbose_name='CNS Date'),
        ),
        migrations.AlterField(
            model_name='creditnotesupplier',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partially Adjusted'), ('adjusted', 'Fully Adjusted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='debitnotecustomer',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_customer_adjusted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnotecustomer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_customer_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnotecustomer',
            name='bookings',
            field=models.ManyToManyField(blank=True, to='team.ManualBooking', verbose_name='Adjusted Bookings'),
        ),
        migrations.AlterField(
            model_name='debitnotecustomer',
            name='date',
            field=models.DateField(verbose_name='DNC Date'),
        ),
        migrations.AlterField(
            model_name='debitnotecustomer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partially Adjusted'), ('adjusted', 'Fully Adjusted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='debitnotesupplier',
            name='date',
            field=models.DateField(verbose_name='DNS Date'),
        ),
        migrations.AlterField(
            model_name='debitnotesupplierdirectadvance',
            name='date',
            field=models.DateField(verbose_name='DNSA Date'),
        ),
        migrations.AlterField(
            model_name='historicalcreditnotecustomer',
            name='date',
            field=models.DateField(verbose_name='CNC Date'),
        ),
        migrations.AlterField(
            model_name='historicalcreditnotecustomerdirectadvance',
            name='date',
            field=models.DateField(verbose_name='CNSA Date'),
        ),
        migrations.AlterField(
            model_name='historicalcreditnotesupplier',
            name='date',
            field=models.DateField(verbose_name='CNS Date'),
        ),
        migrations.AlterField(
            model_name='historicalcreditnotesupplier',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partially Adjusted'), ('adjusted', 'Fully Adjusted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldebitnotecustomer',
            name='date',
            field=models.DateField(verbose_name='DNC Date'),
        ),
        migrations.AlterField(
            model_name='historicaldebitnotecustomer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partially Adjusted'), ('adjusted', 'Fully Adjusted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldebitnotesupplier',
            name='date',
            field=models.DateField(verbose_name='DNS Date'),
        ),
        migrations.AlterField(
            model_name='historicaldebitnotesupplierdirectadvance',
            name='date',
            field=models.DateField(verbose_name='DNSA Date'),
        ),
    ]
