# Generated by Django 2.0.5 on 2018-06-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0102_auto_20180620_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='CNC Date'),
        ),
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='issued_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partially Adjusted'), ('adjusted', 'Fully Adjusted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcreditnotecustomer',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='CNC Date'),
        ),
        migrations.AlterField(
            model_name='historicalcreditnotecustomer',
            name='issued_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcreditnotecustomer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partially Adjusted'), ('adjusted', 'Fully Adjusted')], default='pending', max_length=20),
        ),
    ]
