# Generated by Django 2.0.5 on 2018-06-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0104_auto_20180621_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='credit_note_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcreditnotecustomer',
            name='credit_note_number',
            field=models.CharField(db_index=True, max_length=16),
        ),
    ]
