# Generated by Django 2.0.5 on 2018-06-22 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0107_auto_20180622_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotecustomer',
            name='rejected_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnotecustomer',
            name='rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnotecustomer',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnotecustomerdirectadvance',
            name='rejected_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_advance_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnotecustomerdirectadvance',
            name='rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnotecustomerdirectadvance',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnotesupplier',
            name='rejected_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_supplier_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnotesupplier',
            name='rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnotesupplier',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnotecustomer',
            name='rejected_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_customer_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debitnotecustomer',
            name='rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnotecustomer',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnotesupplier',
            name='rejected_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_supplier_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debitnotesupplier',
            name='rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnotesupplier',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnotesupplierdirectadvance',
            name='rejected_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_supplier_advance_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debitnotesupplierdirectadvance',
            name='rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnotesupplierdirectadvance',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcreditnotecustomer',
            name='rejected_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcreditnotecustomer',
            name='rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcreditnotecustomer',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcreditnotecustomerdirectadvance',
            name='rejected_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcreditnotecustomerdirectadvance',
            name='rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcreditnotecustomerdirectadvance',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcreditnotesupplier',
            name='rejected_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcreditnotesupplier',
            name='rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcreditnotesupplier',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldebitnotecustomer',
            name='rejected_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldebitnotecustomer',
            name='rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldebitnotecustomer',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldebitnotesupplier',
            name='rejected_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldebitnotesupplier',
            name='rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldebitnotesupplier',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldebitnotesupplierdirectadvance',
            name='rejected_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldebitnotesupplierdirectadvance',
            name='rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldebitnotesupplierdirectadvance',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditnotecustomerdirectadvance',
            name='changed_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_advance_changed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
