# Generated by Django 2.0.5 on 2018-06-26 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0110_auto_20180622_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='rejected_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnotecustomerdirectadvance',
            name='rejected_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_advance_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnotecustomerdirectadvance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partially Adjusted'), ('adjusted', 'Fully Adjusted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditnotesupplier',
            name='rejected_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_supplier_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnotecustomer',
            name='rejected_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_customer_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnotesupplier',
            name='rejected_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_supplier_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnotesupplier',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partially Adjusted'), ('adjusted', 'Fully Adjusted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='debitnotesupplierdirectadvance',
            name='rejected_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_supplier_advance_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnotesupplierdirectadvance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partially Adjusted'), ('adjusted', 'Fully Adjusted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcreditnotecustomerdirectadvance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partially Adjusted'), ('adjusted', 'Fully Adjusted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldebitnotesupplier',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partially Adjusted'), ('adjusted', 'Fully Adjusted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldebitnotesupplierdirectadvance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partially Adjusted'), ('adjusted', 'Fully Adjusted')], default='pending', max_length=20),
        ),
    ]
