# Generated by Django 2.0.5 on 2018-06-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0111_auto_20180626_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardpayment',
            name='adjusted_outward_payments',
            field=models.ManyToManyField(blank=True, related_name='_outwardpayment_adjusted_outward_payments_+', to='team.OutWardPayment'),
        ),
        migrations.AlterField(
            model_name='historicaloutwardpayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT'), ('imps', 'IMPS'), ('rtgs', 'RTGS'), ('happay', 'Happay'), ('fuel_card', 'Fuel Card'), ('hdfc_internal_account', 'HDFC Internal Account'), ('adjustment', 'Adjustment')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='outwardpayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT'), ('imps', 'IMPS'), ('rtgs', 'RTGS'), ('happay', 'Happay'), ('fuel_card', 'Fuel Card'), ('hdfc_internal_account', 'HDFC Internal Account'), ('adjustment', 'Adjustment')], max_length=60, null=True),
        ),
    ]
