# Generated by Django 2.0.5 on 2018-07-06 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0112_auto_20180630_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingInwardPaymentCreditDebitNoteCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusted_amount', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_inward_cdn_changed_by', to=settings.AUTH_USER_MODEL)),
                ('cnc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.CreditNoteCustomer')),
                ('created_by', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_inward_cdn_created_by', to=settings.AUTH_USER_MODEL)),
                ('dnc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.DebitNoteCustomer')),
            ],
        ),
        migrations.AlterField(
            model_name='creditnotesupplier',
            name='changed_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_supplier_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnotesupplier',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_supplier_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnotesupplier',
            name='bookings',
            field=models.ManyToManyField(blank=True, to='team.ManualBooking', verbose_name='Adjusted Bookings'),
        ),
    ]
