# Generated by Django 2.0.5 on 2018-07-06 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0113_auto_20180706_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginwardpaymentcreditdebitnotecustomer',
            name='pending_inward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.PendingInwardPaymentEntry'),
        ),
    ]
