# Generated by Django 2.0.5 on 2018-07-07 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0114_pendinginwardpaymentcreditdebitnotecustomer_pending_inward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_adjusted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='changed_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnotecustomerdirectadvance',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_advance_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnotecustomer',
            name='changed_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_customer_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnotecustomer',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_customer_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnotesupplier',
            name='changed_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_supplier_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnotesupplier',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_supplier_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnotesupplierdirectadvance',
            name='changed_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_supplier_advance_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnotesupplierdirectadvance',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_supplier_advance_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outwardpayment',
            name='changed_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outward_payment_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendinginwardpaymententry',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_payment_adjusted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
