# Generated by Django 2.0.5 on 2018-08-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0116_auto_20180803_1211'),
        ('team', '0116_auto_20180726_1655'),
    ]

    operations = [
    ]
