# Generated by Django 2.0.5 on 2018-08-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0117_merge_20180810_1221'),
        ('team', '0117_merge_20180810_1311'),
    ]

    operations = [
    ]
