# Generated by Django 2.0.5 on 2018-08-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0118_merge_20180811_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outwardpayment',
            options={'ordering': ('-id',)},
        ),
    ]
