# Generated by Django 2.0.5 on 2018-08-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0120_historicalmanualbookingsummary_manualbookingsummary'),
        ('team', '0119_auto_20180816_1343'),
    ]

    operations = [
    ]
