# Generated by Django 2.0.5 on 2018-08-21 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0121_merge_20180816_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=10)),
                ('color_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='historicalmanualbooking',
            name='booking_status_color',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='team.BookingStatusColor'),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='booking_status_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.BookingStatusColor'),
        ),
    ]
