# Generated by Django 2.0.5 on 2018-08-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0117_merge_20180809_1021'),
        ('team', '0122_auto_20180821_1319'),
    ]

    operations = [
    ]
