# Generated by Django 2.0.5 on 2018-09-07 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0020_auto_20180905_1312'),
        ('team', '0122_auto_20180821_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanualbookingsummary',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='owner.Vehicle'),
        ),
        migrations.AddField(
            model_name='manualbookingsummary',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.Vehicle'),
        ),
        migrations.AlterField(
            model_name='manualbookingsummary',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
