# Generated by Django 2.0.5 on 2018-09-07 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0123_merge_20180822_1417'),
        ('team', '0123_auto_20180907_0047'),
    ]

    operations = [
    ]
