# Generated by Django 2.0.5 on 2018-10-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0124_merge_20180907_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloutwardpayment',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='historicaloutwardpayment',
            name='utr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outwardpayment',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='outwardpayment',
            name='utr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloutwardpayment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Not Paid'), ('reconciled', 'Reconciled')], default='unpaid', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='outwardpayment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Not Paid'), ('reconciled', 'Reconciled')], default='unpaid', max_length=35, null=True),
        ),
    ]
