# Generated by Django 2.0.5 on 2018-10-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0126_lrs3upload_manualbookings3upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmanualbooking',
            name='invoice_status',
            field=models.CharField(choices=[('no_invoice', 'NoInvoice'), ('invoice_raised', 'InvoiceRaised'), ('invoice_sent', 'InvoiceSent'), ('invoice_confirmed', 'InvoiceConfirmed')], default='no_invoice', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='manualbooking',
            name='invoice_status',
            field=models.CharField(choices=[('no_invoice', 'NoInvoice'), ('invoice_raised', 'InvoiceRaised'), ('invoice_sent', 'InvoiceSent'), ('invoice_confirmed', 'InvoiceConfirmed')], default='no_invoice', max_length=35, null=True),
        ),
    ]
