# Generated by Django 2.0.5 on 2018-12-02 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0129_auto_20181117_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotecustomer',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.Invoice'),
        ),
        migrations.AlterField(
            model_name='creditnotecustomerdirectadvance',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.Invoice'),
        ),
        migrations.AlterField(
            model_name='creditnotesupplier',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.Invoice'),
        ),
        migrations.AlterField(
            model_name='debitnotecustomer',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.Invoice'),
        ),
        migrations.AlterField(
            model_name='debitnotesupplier',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.Invoice'),
        ),
        migrations.AlterField(
            model_name='debitnotesupplierdirectadvance',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.Invoice'),
        ),
    ]
