# Generated by Django 2.0.5 on 2018-12-20 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0027_auto_20180821_1919'),
        ('team', '0130_auto_20181202_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloutwardpayment',
            name='aaho_office',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='utils.AahoOffice'),
        ),
        migrations.AddField(
            model_name='outwardpayment',
            name='aaho_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.AahoOffice'),
        ),
        migrations.AlterField(
            model_name='datatablesfilter',
            name='table_name',
            field=models.CharField(choices=[('MBS', 'Manual Bookings'), ('INV', 'Invoices'), ('OWP', 'Outward Payments'), ('IWP', 'Inward Payments'), ('CUS', 'Customers'), ('SUP', 'Suppliers'), ('OWN', 'Owners'), ('VEH', 'Vehicles'), ('DRV', 'Driver'), ('BAC', 'Bank Account'), ('INS', 'Invoice Summary'), ('POD', 'POD List'), ('OPR', 'Outward Payment Receipt'), ('LRD', 'Lorry Receipt'), ('GPS', 'GPS Devices'), ('CBL', 'Customer Bookings')], max_length=15, unique=True),
        ),
    ]
