# Generated by Django 2.0.5 on 2019-03-13 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0028_auto_20190313_0105'),
        ('team', '0132_auto_20190221_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotecustomerdirectadvance',
            name='accounting_supplier',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_customer_da_supplier', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='creditnotesupplier',
            name='accounting_supplier',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_supplier', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='debitnotesupplier',
            name='accounting_supplier',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='debitnotesupplierdirectadvance',
            name='accounting_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='historicalcreditnotecustomerdirectadvance',
            name='accounting_supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='historicalcreditnotesupplier',
            name='accounting_supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='historicaldebitnotesupplier',
            name='accounting_supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='historicaldebitnotesupplierdirectadvance',
            name='accounting_supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='historicalmanualbooking',
            name='accounting_supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='historicalmanualbooking',
            name='booking_supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='historicalmanualbooking',
            name='driver_supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.Driver'),
        ),
        migrations.AddField(
            model_name='historicalmanualbooking',
            name='owner_supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='historicalmanualbooking',
            name='supplier_vehicle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.Vehicle'),
        ),
        migrations.AddField(
            model_name='historicalmanualbookingsummary',
            name='supplier_vehicle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.Vehicle'),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='accounting_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manualbooking_accounting_supplier', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='booking_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manualbooking_booking_supplier', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='driver_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Driver', verbose_name='Supplier Driver'),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='owner_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manualbooking_owner_supplier', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='supplier_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Vehicle', verbose_name='Vehicle'),
        ),
        migrations.AddField(
            model_name='manualbookingsummary',
            name='supplier_vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Vehicle'),
        ),
        migrations.AlterField(
            model_name='creditnotecustomerdirectadvance',
            name='broker',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.Broker'),
        ),
    ]
