# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20170407_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
