# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_databaseupdatelog_fieldchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0005_employeeoffice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeoffice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeeoffice',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeoffice',
            name='office',
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_office', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_multiple',
            field=models.ManyToManyField(related_name='employee_office_multiple', to='utils.AahoOffice'),
        ),
        migrations.DeleteModel(
            name='EmployeeOffice',
        ),
    ]
