# Generated by Django 2.0.2 on 2018-05-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20170520_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='taskemail',
            name='employee',
            field=models.ManyToManyField(limit_choices_to={'status': 'active'}, to='employee.Employee'),
        ),
    ]
