# Generated by Django 2.0.2 on 2018-05-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20180513_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
