# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_keyvaluestore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakesms',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='KeyValueStore',
        ),
        migrations.DeleteModel(
            name='FakeSms',
        ),
        migrations.DeleteModel(
            name='FakeSmsNumber',
        ),
    ]
