# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170219_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=63)),
                ('folder', models.CharField(max_length=50)),
                ('uuid', models.CharField(max_length=22, unique=True)),
                ('filename', models.CharField(max_length=50, unique=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('uploaded_on', models.DateTimeField(null=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
