# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_s3upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3upload',
            name='uuid',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
