# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170224_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentfile',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
