# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170224_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3upload',
            name='uuid',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
