# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_databaseupdatelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseupdatelog',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='DatabaseUpdateLog',
        ),
    ]
