# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170513_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3upload',
            name='filename',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='s3upload',
            name='folder',
            field=models.CharField(max_length=150),
        ),
    ]
