# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171026_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3upload',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='s3upload',
            name='uuid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
