# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180219_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3upload',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
