# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_s3upload_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3upload',
            name='filename',
            field=models.CharField(max_length=150),
        ),
    ]
