# Generated by Django 2.0.5 on 2018-06-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180405_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3upload',
            name='deleted_on',
        ),
    ]
