# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('alt_email', models.EmailField(max_length=50, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('otp', models.CharField(max_length=8)),
            ],
        ),
    ]
