# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_otp_alt_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
