# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20170403_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('otp', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('otp', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
