# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-01 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0004_auto_20170403_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=70, null=True)),
                ('destination', models.CharField(blank=True, max_length=70, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_route', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteFreight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_point', models.CharField(blank=True, max_length=200, null=True)),
                ('unloading_point', models.CharField(blank=True, max_length=200, null=True)),
                ('freight', models.IntegerField(blank=True, default=0, help_text='Frieght Per Ton', null=True)),
                ('material', models.CharField(blank=True, max_length=300, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_route_freight', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_route_rate', to='index.Route')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('source', 'destination')]),
        ),
    ]
