# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-09 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_routefreight_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_point', models.CharField(blank=True, max_length=70, null=True)),
                ('unloading_point', models.CharField(blank=True, max_length=70, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='routefreight',
            name='loading_point',
        ),
        migrations.RemoveField(
            model_name='routefreight',
            name='unloading_point',
        ),
        migrations.AlterField(
            model_name='routefreight',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_sub_route_rate', to='index.SubRoute'),
        ),
        migrations.AddField(
            model_name='subroute',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_route_rate', to='index.Route'),
        ),
        migrations.AlterUniqueTogether(
            name='subroute',
            unique_together=set([('loading_point', 'unloading_point')]),
        ),
    ]
