# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-10 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20170809_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='routefreight',
            name='truck_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routefreight',
            name='freight',
            field=models.CharField(blank=True, help_text='Frieght Per Ton', max_length=100, null=True),
        ),
    ]
